import React, { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { useListProviders, customFetch } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BarChart3, Download, Search, Building2, MapPin, CheckCircle2, XCircle, AlertTriangle, TrendingUp, Filter, Globe, ShieldCheck, CreditCard, ChevronRight, Activity, Network, Layers, FileText, ExternalLink, Package2, Truck } from "lucide-react";
import { Link } from "wouter";
import { motion } from "framer-motion";

type ServiceEntry = { name: string; count: number };
type ServiceMatrix = { services?: string[]; providers?: Array<{ id: number; clinicName: string; city: string | null; state: string | null; verificationStatus: string; tpaFriendly: boolean; services: Record<string, boolean> }> };
type CoverageGaps = { services?: string[]; states?: string[]; gaps?: Array<Record<string, number> & { state: string }>; serviceSummary?: Array<{ service: string; statesCovered: number; totalStates: number; gapStates: number }> };
type SupplyVendor = { name: string; openOrders: number; lastDelivery: string; nextETA: string; stockStatus: "On Track" | "Watch" | "Delayed"; clinicCount: number };
type SupplyLine = { item: string; unit: string; qtySent: number; qtyReceived: number; shipDate: string; clinicName: string; clinicAddress: string; tracking: string; carrier: "FedEx" | "Local"; section: string };
type ClinicNews = { clinic: string; city: string; state: string; headline: string; type: "Opening" | "Closing" | "Expansion" | "Relocation" | "Leadership"; date: string; notes: string };

const KNOWN_SERVICES = ["Drug Testing", "DOT Physicals", "Physical Exams", "Chest X-Ray", "Audiometry", "Vision Testing", "Pulmonary Function", "Spirometry", "Stress Testing", "EKG", "Lab Work", "Urine Testing", "Hair Testing", "Breath Alcohol", "MRO Services", "Urgent Care", "Occupational Therapy", "Workers Comp", "Pre-Employment"];
function safeText(value: unknown, fallback = "") { const text = String(value ?? "").trim(); return text || fallback; }
function includesText(value: unknown, query: string) { return safeText(value).toLowerCase().includes(query.toLowerCase()); }
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }

export default function Analyst() {
  const [activeTab, setActiveTab] = useState("service-search");
  const [selectedServices, setSelectedServices] = useState<string[]>([]);
  const [stateFilter, setStateFilter] = useState("");
  const [verifyFilter, setVerifyFilter] = useState("");
  const [tpaOnly, setTpaOnly] = useState(false);
  const [textSearch, setTextSearch] = useState("");
  const [matrixSearch, setMatrixSearch] = useState("");
  const [exportState, setExportState] = useState("");
  const [exportService, setExportService] = useState("");
  const [exportVerify, setExportVerify] = useState("");
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);
  const [supplySearch, setSupplySearch] = useState("");
  const [supplyForm, setSupplyForm] = useState({ clinicName: "", clinicAddress: "", section: "", item: "", unit: "", qtySent: "", qtyReceived: "", shipDate: "", tracking: "", carrier: "FedEx", vendor: "Labcorp" });
  const [newsSearch, setNewsSearch] = useState("");

  const { data: allProviders, isLoading: loadingProviders } = useListProviders();
  const { data: services, isLoading: loadingServices } = useQuery<ServiceEntry[]>({ queryKey: ["/api/analytics/services"], queryFn: () => customFetch("/api/analytics/services") });
  const { data: matrix, isLoading: loadingMatrix } = useQuery<ServiceMatrix>({ queryKey: ["/api/analytics/service-matrix"], queryFn: () => customFetch("/api/analytics/service-matrix"), enabled: activeTab === "service-matrix" });
  const { data: gaps, isLoading: loadingGaps } = useQuery<CoverageGaps>({ queryKey: ["/api/analytics/coverage-gaps"], queryFn: () => customFetch("/api/analytics/coverage-gaps"), enabled: activeTab === "coverage-gaps" });

  const supplyVendors: SupplyVendor[] = [{ name: "Labcorp", openOrders: 14, lastDelivery: "May 1", nextETA: "May 6", stockStatus: "Watch", clinicCount: 22 }, { name: "CRL", openOrders: 9, lastDelivery: "Apr 29", nextETA: "May 5", stockStatus: "On Track", clinicCount: 17 }];
  const [supplyLines, setSupplyLines] = useState<SupplyLine[]>([{ item: "KAB Reqs", unit: "packs", qtySent: 24, qtyReceived: 22, shipDate: "2026-05-01", clinicName: "Northside Occ Med", clinicAddress: "1200 Main St, Dallas, TX", tracking: "4490 1234 5678", carrier: "FedEx", section: "Requests" }, { item: "COCs", unit: "booklets", qtySent: 40, qtyReceived: 40, shipDate: "2026-05-02", clinicName: "Northside Occ Med", clinicAddress: "1200 Main St, Dallas, TX", tracking: "4490 1234 8899", carrier: "FedEx", section: "Forms" }, { item: "Blood Collection Tubes", unit: "cases", qtySent: 8, qtyReceived: 8, shipDate: "2026-05-01", clinicName: "Riverbend Clinic", clinicAddress: "44 River Rd, Tampa, FL", tracking: "CRL-77821", carrier: "Local", section: "Specimen" }]);
  const clinicNews: ClinicNews[] = [{ clinic: "Northside Occ Med", city: "Dallas", state: "TX", headline: "Opened new satellite draw site", type: "Opening", date: "2026-05-02", notes: "Expanded same-day testing capacity for employer walk-ins." }, { clinic: "Riverbend Clinic", city: "Tampa", state: "FL", headline: "Added onsite heavy metal collection lane", type: "Expansion", date: "2026-05-01", notes: "Requested higher tube volume and extra courier pickups." }, { clinic: "Lakeside Health", city: "Phoenix", state: "AZ", headline: "Closed evening hours at one location", type: "Closing", date: "2026-04-30", notes: "May shift some collections to nearby partner sites." }];

  const toggleService = (svc: string) => setSelectedServices((prev) => prev.includes(svc) ? prev.filter((s) => s !== svc) : [...prev, svc]);
  const providers = Array.isArray(allProviders) ? allProviders : [];
  const filteredProviders = useMemo(() => providers.filter((p) => { const q = textSearch.trim().toLowerCase(); if (q && ![p.clinicName, p.city, p.state, p.address, p.servicesOffered].some((v) => includesText(v, q))) return false; if (stateFilter && safeText(p.state).toUpperCase() !== stateFilter.toUpperCase()) return false; if (verifyFilter && p.verificationStatus !== verifyFilter) return false; if (tpaOnly && !(p.tpaFriendlyClues || p.employerAccountClues || p.corporateBillingClues)) return false; if (selectedServices.length > 0) { const provSvcs = safeText(p.servicesOffered).toLowerCase(); if (!selectedServices.every((s) => provSvcs.includes(s.toLowerCase()))) return false; } return true; }), [providers, textSearch, stateFilter, verifyFilter, tpaOnly, selectedServices]);
  const allStates = useMemo(() => Array.from(new Set(providers.map((p) => p.state).filter(Boolean))).sort() as string[], [providers]);
  const networkStats = useMemo(() => { const verified = providers.filter((p) => p.verificationStatus === "Verified").length; const tpa = providers.filter((p) => p.tpaFriendlyClues || p.employerAccountClues || p.corporateBillingClues).length; const mapped = providers.filter((p) => p.latitude || p.longitude).length; const states = new Set(providers.map((p) => p.state).filter(Boolean)).size; const multiSource = providers.filter((p) => Number(p.sourceCount || 0) > 1).length; return { total: providers.length, verified, tpa, mapped, states, multiSource }; }, [providers]);
  const filteredMatrix = useMemo(() => { if (!matrix) return { services: [], providers: [] }; const rows = list(matrix.providers); if (!matrixSearch.trim()) return { ...matrix, providers: rows, services: list(matrix.services) }; const q = matrixSearch.toLowerCase(); return { ...matrix, services: list(matrix.services), providers: rows.filter((p) => [p.clinicName, p.state, p.city, p.verificationStatus].some((v) => includesText(v, q))) }; }, [matrix, matrixSearch]);

  const makeAnalyticsParams = () => { const params = new URLSearchParams(); if (exportState) params.set("state", exportState); if (exportService) params.set("service", exportService); if (exportVerify) params.set("verificationStatus", exportVerify); return params.toString(); };
  const handleGenerateReport = () => window.open(`/api/analytics/report${makeAnalyticsParams() ? `?${makeAnalyticsParams()}` : ""}`, "_blank");
  const handleExport = async () => { setIsExporting(true); setExportError(null); try { const url = `/api/analytics/export${makeAnalyticsParams() ? `?${makeAnalyticsParams()}` : ""}`; const response = await fetch(url); if (!response.ok) throw new Error(`Export failed: ${response.status}`); const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `occu-med-providers-${Date.now()}.csv`; link.click(); URL.revokeObjectURL(link.href); } catch (err) { setExportError(err instanceof Error ? err.message : "Export failed."); } finally { setIsExporting(false); } };

  const topServices = list(services).slice(0, 18);
  const displayServices = topServices.length > 0 ? topServices : KNOWN_SERVICES.slice(0, 16).map((s) => ({ name: s.toUpperCase(), count: 0 }));
  const filteredSupplies = supplyVendors.filter((v) => includesText(v.name, supplySearch));
  const filteredClinicNews = clinicNews.filter((n) => [n.clinic, n.city, n.state, n.headline, n.notes].some((v) => includesText(v, newsSearch)));
  const supplyTotals = supplyLines.reduce((acc, line) => { acc.sent += Number(line.qtySent || 0); acc.received += Number(line.qtyReceived || 0); acc.pending += Math.max(Number(line.qtySent || 0) - Number(line.qtyReceived || 0), 0); return acc; }, { sent: 0, received: 0, pending: 0 });
  const addSupplyLine = () => { if (!supplyForm.item || !supplyForm.clinicName || !supplyForm.shipDate) return; setSupplyLines((prev) => [{ item: supplyForm.item, unit: supplyForm.unit || "units", qtySent: Number(supplyForm.qtySent || 0), qtyReceived: Number(supplyForm.qtyReceived || 0), shipDate: supplyForm.shipDate, clinicName: supplyForm.clinicName, clinicAddress: supplyForm.clinicAddress, tracking: supplyForm.tracking || "Pending", carrier: supplyForm.carrier as "FedEx" | "Local", section: supplyForm.section || "General" }, ...prev]); setSupplyForm({ clinicName: "", clinicAddress: "", section: "", item: "", unit: "", qtySent: "", qtyReceived: "", shipDate: "", tracking: "", carrier: "FedEx", vendor: "Labcorp" }); };

  return <div className="space-y-6 pb-12"><div><h1 className="text-3xl font-bold tracking-tight text-white flex items-center gap-3"><BarChart3 className="h-8 w-8 text-primary drop-shadow-[0_0_12px_rgba(18,173,165,0.55)]" />Analyst Tools</h1><p className="text-muted-foreground mt-2 text-sm max-w-2xl leading-relaxed">Analyze provider services, coverage gaps, exports, and lightweight local tracking utilities.</p></div>
    <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6"><TabsList className="bg-black/40 border border-white/[0.08] p-1 rounded-xl h-auto flex flex-wrap gap-1"><Tab value="service-search" icon={<Search className="h-3.5 w-3.5 mr-2" />} label="Service Search" /><Tab value="service-matrix" icon={<Layers className="h-3.5 w-3.5 mr-2" />} label="Service Matrix" /><Tab value="coverage-gaps" icon={<Network className="h-3.5 w-3.5 mr-2" />} label="Coverage Gaps" /><Tab value="export" icon={<Download className="h-3.5 w-3.5 mr-2" />} label="Exports" /><Tab value="supplies" icon={<Package2 className="h-3.5 w-3.5 mr-2" />} label="Supplies" /><Tab value="clinic-news" icon={<Globe className="h-3.5 w-3.5 mr-2" />} label="Clinic News" /></TabsList>
      <TabsContent value="service-search" className="space-y-5"><Stats stats={networkStats} /><Card className="glass-panel border-white/[0.06] bg-black/35"><CardContent className="p-5 space-y-4"><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><Input placeholder="Search provider, city, service…" value={textSearch} onChange={(e) => setTextSearch(e.target.value)} className="bg-black/40 border-white/10 text-white" /><select value={stateFilter} onChange={(e)=>setStateFilter(e.target.value)} className="bg-black/40 border border-white/10 rounded-md px-3 py-2 text-white"><option value="">All states</option>{allStates.map((s)=><option key={s} value={s}>{s}</option>)}</select><select value={verifyFilter} onChange={(e)=>setVerifyFilter(e.target.value)} className="bg-black/40 border border-white/10 rounded-md px-3 py-2 text-white"><option value="">All verification</option><option value="Verified">Verified</option><option value="Unverified">Unverified</option></select><label className="flex items-center gap-2 text-sm text-muted-foreground"><input type="checkbox" checked={tpaOnly} onChange={(e)=>setTpaOnly(e.target.checked)} /> TPA/corporate clues</label></div><div className="flex flex-wrap gap-2">{displayServices.map((svc)=><button key={svc.name} onClick={()=>toggleService(svc.name)} className={`rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wider ${selectedServices.includes(svc.name) ? "border-primary/40 bg-primary/15 text-primary" : "border-white/10 bg-white/[0.03] text-muted-foreground hover:text-white"}`}>{svc.name} <span className="opacity-60">{svc.count}</span></button>)}</div></CardContent></Card>{loadingProviders ? <Skeleton className="h-40 w-full bg-white/5 rounded-xl" /> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{filteredProviders.map((p)=><ProviderCard key={p.id} p={p} />)}</div>}</TabsContent>
      <TabsContent value="service-matrix" className="space-y-5"><Input placeholder="Search matrix provider…" value={matrixSearch} onChange={(e)=>setMatrixSearch(e.target.value)} className="max-w-md bg-black/40 border-white/10 text-white" />{loadingMatrix ? <Skeleton className="h-80 w-full bg-white/5 rounded-xl" /> : <Card className="glass-panel border-white/[0.06] bg-black/35 overflow-x-auto"><CardContent className="p-0"><table className="w-full text-sm"><thead><tr className="border-b border-white/10"><th className="text-left p-3 text-muted-foreground">Provider</th>{list(filteredMatrix.services).slice(0,12).map((s)=><th key={s} className="p-3 text-muted-foreground text-xs">{s}</th>)}</tr></thead><tbody>{list(filteredMatrix.providers).map((p)=><tr key={p.id} className="border-b border-white/[0.04]"><td className="p-3 font-bold text-white">{safeText(p.clinicName,"Unknown")}</td>{list(filteredMatrix.services).slice(0,12).map((s)=><td key={s} className="p-3 text-center">{p.services?.[s] ? <CheckCircle2 className="h-4 w-4 text-lime-300 mx-auto" /> : <XCircle className="h-4 w-4 text-muted-foreground/40 mx-auto" />}</td>)}</tr>)}</tbody></table></CardContent></Card>}</TabsContent>
      <TabsContent value="coverage-gaps" className="space-y-5">{loadingGaps ? <Skeleton className="h-80 w-full bg-white/5 rounded-xl" /> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{list(gaps?.serviceSummary).map((g)=><Card key={g.service} className="glass-panel border-white/[0.06] bg-black/35"><CardContent className="p-4"><div className="flex justify-between"><div className="font-bold text-white">{g.service}</div><Badge className="bg-primary/10 text-primary border-primary/20">{g.statesCovered}/{g.totalStates} states</Badge></div><div className="text-xs text-muted-foreground mt-2">Gap states: {g.gapStates}</div></CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="export" className="space-y-5"><Card className="glass-panel border-white/[0.06] bg-black/35"><CardContent className="p-5 space-y-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><select value={exportState} onChange={(e)=>setExportState(e.target.value)} className="bg-black/40 border border-white/10 rounded-md px-3 py-2 text-white"><option value="">All states</option>{allStates.map((s)=><option key={s} value={s}>{s}</option>)}</select><Input placeholder="Service contains…" value={exportService} onChange={(e)=>setExportService(e.target.value)} className="bg-black/40 border-white/10 text-white" /><select value={exportVerify} onChange={(e)=>setExportVerify(e.target.value)} className="bg-black/40 border border-white/10 rounded-md px-3 py-2 text-white"><option value="">Any verification</option><option value="Verified">Verified</option><option value="Unverified">Unverified</option></select></div><div className="flex gap-2"><Button onClick={handleGenerateReport} className="bg-primary/20 border border-primary/30 text-primary hover:bg-primary/30"><FileText className="h-4 w-4 mr-2" />Open Report</Button><Button onClick={handleExport} disabled={isExporting} variant="outline" className="border-white/10 bg-black/30 text-muted-foreground hover:text-white"><Download className="h-4 w-4 mr-2" />{isExporting ? "Exporting…" : "Export CSV"}</Button></div>{exportError && <div className="rounded-lg border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{exportError}</div>}</CardContent></Card></TabsContent>
      <TabsContent value="supplies" className="space-y-5"><LocalOnlyNotice /><div className="grid grid-cols-3 gap-3"><Metric label="Sent" value={supplyTotals.sent} /><Metric label="Received" value={supplyTotals.received} green /><Metric label="Pending" value={supplyTotals.pending} red /></div><Input placeholder="Search vendors…" value={supplySearch} onChange={(e)=>setSupplySearch(e.target.value)} className="max-w-md bg-black/40 border-white/10 text-white" /><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{filteredSupplies.map((v)=><Card key={v.name} className="glass-panel border-white/[0.06] bg-black/35"><CardContent className="p-4"><div className="font-bold text-white">{v.name}</div><div className="text-xs text-muted-foreground">Open orders: {v.openOrders} · Status: {v.stockStatus}</div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="clinic-news" className="space-y-5"><LocalOnlyNotice /><Input placeholder="Search local clinic news…" value={newsSearch} onChange={(e)=>setNewsSearch(e.target.value)} className="max-w-md bg-black/40 border-white/10 text-white" /><div className="space-y-3">{filteredClinicNews.map((n)=><Card key={`${n.clinic}-${n.date}`} className="glass-panel border-white/[0.06] bg-black/35"><CardContent className="p-4"><div className="flex items-center justify-between"><div className="font-bold text-white">{n.headline}</div><Badge className="bg-primary/10 text-primary border-primary/20">{n.type}</Badge></div><div className="text-sm text-muted-foreground mt-1">{n.clinic} · {n.city}, {n.state} · {n.date}</div><div className="text-sm text-white/80 mt-2">{n.notes}</div></CardContent></Card>)}</div></TabsContent>
    </Tabs></div>;
}

function Tab({ value, icon, label }: { value: string; icon: React.ReactNode; label: string }) { return <TabsTrigger value={value} className="data-[state=active]:bg-primary data-[state=active]:text-black data-[state=active]:font-bold rounded-lg px-4 py-2 text-sm text-muted-foreground">{icon}{label}</TabsTrigger>; }
function Stats({ stats }: { stats: { total: number; verified: number; tpa: number; mapped: number; states: number; multiSource: number } }) { return <div className="grid grid-cols-2 md:grid-cols-6 gap-3">{Object.entries(stats).map(([k,v])=><Metric key={k} label={k} value={v as number} />)}</div>; }
function Metric({ label, value, green, red }: { label: string; value: number; green?: boolean; red?: boolean }) { return <div className="glass-panel border border-white/[0.06] rounded-xl p-4 text-center"><div className={`text-2xl font-black ${red ? "text-red-400" : green ? "text-lime-300" : "text-primary"}`}>{value}</div><div className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">{label}</div></div>; }
function ProviderCard({ p }: { p: any }) { return <Link href={`/providers/${p.id}`}><motion.div whileHover={{ y: -2 }} className="rounded-xl border border-white/[0.06] bg-black/35 p-4 hover:border-primary/30 transition-colors"><div className="flex items-start justify-between gap-3"><div><div className="font-bold text-white">{safeText(p.clinicName, "Unknown Provider")}</div><div className="text-xs text-muted-foreground flex items-center gap-1 mt-1"><MapPin className="h-3 w-3" />{[p.city,p.state].filter(Boolean).join(", ") || "Location unknown"}</div></div><ChevronRight className="h-4 w-4 text-muted-foreground" /></div><div className="flex flex-wrap gap-2 mt-3"><Badge className="bg-primary/10 text-primary border-primary/20">{p.verificationStatus || "Unknown"}</Badge>{(p.tpaFriendlyClues || p.employerAccountClues || p.corporateBillingClues) && <Badge className="bg-lime-500/10 text-lime-300 border-lime-500/20">Corporate Billing</Badge>}</div></motion.div></Link>; }
function LocalOnlyNotice() { return <div className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-sm text-primary flex items-start gap-2"><AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />This section is currently local-only demo data. Entries are not persisted to the backend and may disappear after reload.</div>; }
