import React, { useMemo } from "react";
import { useGetStatesCoverage, useGetProvidersForMap } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Map as MapIcon, Activity, Building2, ShieldCheck, AlertTriangle, MapPin } from "lucide-react";
import { ComposableMap, Geographies, Geography, Marker } from "react-simple-maps";

const geoUrl = "https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json";

const STATE_NAME_TO_ABBR: Record<string, string> = {
  Alabama: "AL", Alaska: "AK", Arizona: "AZ", Arkansas: "AR", California: "CA", Colorado: "CO", Connecticut: "CT", Delaware: "DE", "District of Columbia": "DC", Florida: "FL", Georgia: "GA", Hawaii: "HI", Idaho: "ID", Illinois: "IL", Indiana: "IN", Iowa: "IA", Kansas: "KS", Kentucky: "KY", Louisiana: "LA", Maine: "ME", Maryland: "MD", Massachusetts: "MA", Michigan: "MI", Minnesota: "MN", Mississippi: "MS", Missouri: "MO", Montana: "MT", Nebraska: "NE", Nevada: "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", Ohio: "OH", Oklahoma: "OK", Oregon: "OR", Pennsylvania: "PA", "Rhode Island": "RI", "South Carolina": "SC", "South Dakota": "SD", Tennessee: "TN", Texas: "TX", Utah: "UT", Vermont: "VT", Virginia: "VA", Washington: "WA", "West Virginia": "WV", Wisconsin: "WI", Wyoming: "WY",
};
const STATE_ABBR_TO_NAME = Object.fromEntries(Object.entries(STATE_NAME_TO_ABBR).map(([name, abbr]) => [abbr, name]));

type CoverageRow = { state?: string; providerCount?: number; verifiedCount?: number };
type MapProvider = { id: number | string; latitude?: number | string | null; longitude?: number | string | null; clinicName?: string; state?: string | null };

function n(value: unknown) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function safeText(value: unknown, fallback = "Unknown") { const text = String(value ?? "").trim(); return text || fallback; }
function normalizeState(value: unknown) { const text = safeText(value, "").toUpperCase(); if (text.length === 2) return text; const title = String(value ?? "").trim().replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()); return STATE_NAME_TO_ABBR[title] || text; }
function isValidCoord(lat: unknown, lon: unknown) { const la = Number(lat); const lo = Number(lon); return Number.isFinite(la) && Number.isFinite(lo) && la >= -90 && la <= 90 && lo >= -180 && lo <= 180; }
function getIntensityColor(count: number, maxProviders: number) { if (!count || !maxProviders) return "rgba(255, 255, 255, 0.025)"; const ratio = count / maxProviders; if (ratio > 0.8) return "rgba(18, 173, 165, 0.82)"; if (ratio > 0.5) return "rgba(18, 173, 165, 0.55)"; if (ratio > 0.2) return "rgba(18, 173, 165, 0.32)"; return "rgba(18, 173, 165, 0.16)"; }

export default function MapCoverage() {
  const { data: coverageData, isLoading: isLoadingCoverage } = useGetStatesCoverage();
  const { data: mapProviders, isLoading: isLoadingProviders } = useGetProvidersForMap();
  const coverageRows = Array.isArray(coverageData) ? coverageData as CoverageRow[] : [];
  const providers = Array.isArray(mapProviders) ? mapProviders as MapProvider[] : [];

  const coverageByState = useMemo(() => new Map(coverageRows.map((row) => [normalizeState(row.state), row])), [coverageRows]);
  const maxProviders = Math.max(...coverageRows.map((d) => n(d.providerCount)), 0);
  const totalProviders = coverageRows.reduce((sum, row) => sum + n(row.providerCount), 0);
  const verifiedProviders = coverageRows.reduce((sum, row) => sum + n(row.verifiedCount), 0);
  const mappedProviders = providers.filter((p) => isValidCoord(p.latitude, p.longitude));
  const unmatchedStates = coverageRows.filter((row) => !STATE_ABBR_TO_NAME[normalizeState(row.state)] && !STATE_NAME_TO_ABBR[safeText(row.state)]);
  const topStates = [...coverageRows].sort((a, b) => n(b.providerCount) - n(a.providerCount)).slice(0, 8);

  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight text-white">Geographic Coverage</h1><p className="text-muted-foreground mt-1">Provider density by state, using only mapped provider and coverage data returned by the API.</p></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric icon={<Building2 className="h-4 w-4" />} label="Providers" value={totalProviders} /><Metric icon={<ShieldCheck className="h-4 w-4" />} label="Verified" value={verifiedProviders} green /><Metric icon={<MapPin className="h-4 w-4" />} label="Mapped Pins" value={mappedProviders.length} /><Metric icon={<AlertTriangle className="h-4 w-4" />} label="Unmatched States" value={unmatchedStates.length} red={unmatchedStates.length > 0} /></div>
    {unmatchedStates.length > 0 && <div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">Some coverage rows could not be matched to a U.S. state map shape: {unmatchedStates.map((s) => safeText(s.state)).join(", ")}</div>}
    <Card className="glass-panel border-primary/20 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent pointer-events-none" /><CardHeader className="flex flex-row items-center justify-between pb-2 relative z-10 border-b border-white/[0.05] bg-black/20"><div><CardTitle className="flex items-center gap-2 text-white"><MapIcon className="h-5 w-5 text-primary" />Coverage Map</CardTitle><CardDescription className="text-muted-foreground">State density and mapped provider coordinates</CardDescription></div><div className="flex items-center gap-4 text-xs font-medium text-muted-foreground bg-white/[0.05] px-4 py-2 rounded-lg border border-white/10"><span className="flex items-center gap-1.5"><div className="w-3 h-3 bg-white/5 border border-white/10 rounded-sm" />0</span><span className="flex items-center gap-1.5"><div className="w-3 h-3 bg-primary/30 border border-primary/30 rounded-sm" />Low</span><span className="flex items-center gap-1.5"><div className="w-3 h-3 bg-primary border border-primary shadow-[0_0_8px_rgba(18,173,165,0.8)] rounded-sm" />High</span></div></CardHeader><CardContent className="p-0 relative bg-black/40 min-h-[600px] flex items-center justify-center overflow-hidden"><div className="absolute top-1/2 left-1/2 w-[800px] h-[800px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/[0.03] pointer-events-none" /><div className="absolute top-1/2 left-1/2 w-[400px] h-[400px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/[0.05] pointer-events-none" />{isLoadingCoverage || isLoadingProviders ? <Skeleton className="w-[80%] h-[500px] bg-white/5 rounded-2xl relative z-10" /> : <div className="w-full max-w-5xl relative z-10 drop-shadow-[0_0_30px_rgba(18,173,165,0.15)] p-8"><ComposableMap projection="geoAlbersUsa"><Geographies geography={geoUrl}>{({ geographies }) => geographies.map((geo) => { const stateName = geo.properties.name; const abbr = STATE_NAME_TO_ABBR[stateName]; const stateData = coverageByState.get(abbr) || coverageByState.get(stateName); const count = n(stateData?.providerCount); return <Geography key={geo.rsmKey} geography={geo} fill={getIntensityColor(count, maxProviders)} stroke="rgba(255, 255, 255, 0.15)" strokeWidth={0.5} style={{ default: { outline: "none" }, hover: { fill: "rgba(18, 173, 165, 0.9)", outline: "none", filter: "drop-shadow(0 0 10px rgba(18,173,165,0.8))" }, pressed: { outline: "none" } }} />; })}</Geographies>{mappedProviders.map((provider) => <Marker key={provider.id} coordinates={[Number(provider.longitude), Number(provider.latitude)]}><circle r={2} fill="#fff" className="animate-pulse" /><circle r={6} fill="rgba(18, 173, 165, 0.45)" className="animate-ping" /></Marker>)}</ComposableMap></div>}</CardContent></Card>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Card className="glass-panel border-white/5"><CardHeader className="bg-white/[0.02] border-b border-white/[0.05]"><CardTitle className="text-base flex items-center gap-2 text-white"><Activity className="h-4 w-4 text-primary" />Highest Density Regions</CardTitle></CardHeader><CardContent className="p-6">{isLoadingCoverage ? <div className="space-y-4"><Skeleton className="h-12 w-full bg-white/5 rounded-lg" /><Skeleton className="h-12 w-full bg-white/5 rounded-lg" /></div> : <div className="space-y-3">{topStates.length ? topStates.map((state, i) => <div key={`${safeText(state.state)}-${i}`} className="flex items-center justify-between p-3 rounded-lg bg-black/40 border border-white/[0.05] hover:border-primary/30 transition-colors group"><div className="flex items-center gap-4"><div className="flex items-center justify-center w-6 h-6 rounded-md bg-white/5 text-primary font-bold text-xs border border-white/10 group-hover:bg-primary/20 group-hover:border-primary/50 transition-colors">{i + 1}</div><div><div className="font-semibold text-white tracking-wide">{STATE_ABBR_TO_NAME[normalizeState(state.state)] || safeText(state.state)}</div><div className="text-xs text-muted-foreground">{normalizeState(state.state)}</div></div></div><div className="text-sm font-medium text-muted-foreground bg-white/5 px-3 py-1 rounded-md border border-white/5">{n(state.providerCount)} providers</div></div>) : <div className="text-sm text-muted-foreground text-center py-8">No coverage data returned.</div>}</div>}</CardContent></Card><Card className="glass-panel border-white/5"><CardHeader className="bg-white/[0.02] border-b border-white/[0.05]"><CardTitle className="text-base flex items-center gap-2 text-white"><MapPin className="h-4 w-4 text-primary" />Map Data Quality</CardTitle></CardHeader><CardContent className="p-6 space-y-3 text-sm text-muted-foreground"><div>Coverage shading uses provider counts only when a state can be matched by abbreviation or full state name.</div><div>Provider pins render only when latitude and longitude are valid numeric coordinates.</div><div>No random or placeholder density is used.</div></CardContent></Card></div>
  </div>;
}

function Metric({ icon, label, value, green, red }: { icon: React.ReactNode; label: string; value: number; green?: boolean; red?: boolean }) { return <div className="glass-panel border border-white/[0.06] rounded-xl p-4 text-center"><div className={`mx-auto mb-2 flex h-8 w-8 items-center justify-center rounded-lg border ${red ? "border-red-500/20 bg-red-500/10 text-red-400" : green ? "border-lime-500/20 bg-lime-500/10 text-lime-300" : "border-primary/20 bg-primary/10 text-primary"}`}>{icon}</div><div className={`text-2xl font-black ${red ? "text-red-400" : green ? "text-lime-300" : "text-primary"}`}>{value}</div><div className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">{label}</div></div>; }
