import React, { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { Mail, Printer, FileSignature, CheckCircle2, AlertCircle, XCircle, Send, Copy, Check, Building2, MapPin, Calendar, MessageSquare, Trash2, Plus } from "lucide-react";
import { format, differenceInDays } from "date-fns";

type OutreachRecord = { id: number; providerId: number | null; providerName?: string; providerCity?: string | null; providerState?: string | null; outreachType?: string; templateName?: string | null; subject?: string | null; body?: string | null; recipientEmail?: string | null; recipientFax?: string | null; status?: string; sentAt?: string | null; receivedAt?: string | null; followUpDate?: string | null; notes?: string | null; createdAt?: string };
type OutreachStats = { total?: number; sent?: number; received?: number; signed?: number; overdue?: number };
type OutreachProvider = { id: number; clinicName?: string; city?: string | null; state?: string | null; email?: string | null; fax?: string | null; phone?: string | null; contactPerson?: string | null; servicesOffered?: string | null; verificationStatus?: string; tpaFriendlyClues?: string | null; website?: string | null };
type OutreachTemplate = { id: string; name: string; subject: string; body: string };
type TemplateRenderer = { id: string; name: string; subject: (p: OutreachProvider) => string; body: (p: OutreachProvider) => string };

const STATUS_META: Record<string, { label: string; color: string; icon: React.ElementType }> = { draft: { label: "Draft", color: "text-slate-400 bg-white/5 border-white/10", icon: MessageSquare }, sent: { label: "Sent", color: "text-primary bg-primary/10 border-primary/20", icon: Send }, received: { label: "Received", color: "text-teal-300 bg-teal-500/10 border-teal-500/20", icon: CheckCircle2 }, signed: { label: "Signed", color: "text-lime-300 bg-lime-500/10 border-lime-500/20", icon: FileSignature }, declined: { label: "Declined", color: "text-red-400 bg-red-500/10 border-red-500/20", icon: XCircle }, follow_up_needed: { label: "Follow Up", color: "text-cyan-300 bg-cyan-500/10 border-cyan-500/20", icon: AlertCircle } };
const TEMPLATES: TemplateRenderer[] = [{ id: "service_agreement", name: "Service Agreement Request", subject: (p) => `Service Agreement — ${safeText(p.clinicName, "Clinic")}`, body: (p) => `Dear ${safeText(p.contactPerson, "Clinic Administrator")},\n\nI hope this message finds you well. My name is [Your Name], and I am reaching out on behalf of Occu-Med regarding a possible provider-network relationship with ${safeText(p.clinicName, "your clinic")}${p.city ? ` in ${p.city}, ${p.state || ""}` : ""}.\n\nWe would like to confirm whether your facility can support occupational health referrals, employer account billing, and related documentation requirements.\n\nBest regards,\n[Your Name]` }, { id: "agreement_followup", name: "Agreement Follow-Up (Pending)", subject: (p) => `Follow-Up: Pending Service Agreement — ${safeText(p.clinicName, "Clinic")}`, body: (p) => `Dear ${safeText(p.contactPerson, "Clinic Administrator")},\n\nI am following up on the Service Participation Agreement we sent to ${safeText(p.clinicName, "your clinic")}.\n\nPlease let us know whether it was received and if there are any questions we can help address.\n\nBest regards,\n[Your Name]` }, { id: "initial_outreach", name: "Initial Cold Outreach", subject: (p) => `Network Partnership Opportunity — ${safeText(p.clinicName, "Clinic")}`, body: (p) => `Dear ${safeText(p.contactPerson, "Clinic Director")},\n\nI am reaching out to introduce Occu-Med and explore a potential partnership with ${safeText(p.clinicName, "your clinic")}.\n\nWe coordinate occupational health referrals and would like to confirm your clinic's capabilities, pricing, billing process, and best contact for future referrals.\n\nBest regards,\n[Your Name]` }, { id: "tpa_inquiry", name: "TPA / Corporate Billing Inquiry", subject: (p) => `TPA & Corporate Billing Capabilities — ${safeText(p.clinicName, "Clinic")}`, body: (p) => `Dear ${safeText(p.contactPerson, "Billing Department")},\n\nI am reaching out to ask about TPA and corporate account billing for ${safeText(p.clinicName, "your clinic")}.\n\n1. Do you accept TPA platforms?\n2. Do you maintain employer accounts?\n3. Can you accommodate occupational health referrals billed to employer accounts?\n\nThank you,\n[Your Name]` }, { id: "fax_cover", name: "Fax Cover Sheet", subject: (p) => `FAX — Network Agreement — ${safeText(p.clinicName, "Clinic")}`, body: (p) => `FACSIMILE TRANSMISSION\n\nTO: ${safeText(p.clinicName, "Clinic")}\nFAX: ${safeText(p.fax, "[FAX NUMBER]")}\nDATE: ${format(new Date(), "MMMM d, yyyy")}\nRE: Network Participation Agreement\n\nPlease find enclosed the Occu-Med Network Participation Agreement for your review.\n\nThank you.` }];
function safeText(value: unknown, fallback = "") { const text = String(value ?? "").trim(); return text || fallback; }
function n(value: unknown) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }
function isValidDate(value: unknown) { const d = new Date(String(value || "")); return !Number.isNaN(d.getTime()); }
function isOverdue(record: OutreachRecord) { return record.status === "sent" && isValidDate(record.sentAt) && differenceInDays(new Date(), new Date(String(record.sentAt))) >= 7; }
function requiredRecipient(provider: OutreachProvider, type: "email" | "fax" | "agreement", override = "") { if (type === "fax") return safeText(override || provider.fax); return safeText(override || provider.email); }
function applyTemplate(template: OutreachTemplate, provider: OutreachProvider) { const replacements: Record<string, string> = { "{{clinic_name}}": safeText(provider.clinicName, "the clinic"), "{{city}}": safeText(provider.city), "{{state}}": safeText(provider.state), "{{contact_name}}": safeText(provider.contactPerson, "Clinic Administrator") }; const replace = (text: string) => Object.entries(replacements).reduce((acc, [key, val]) => acc.replaceAll(key, val), text); return { subject: replace(template.subject), body: replace(template.body) }; }
function StatusBadge({ status }: { status?: string }) { const meta = STATUS_META[status || "sent"] || STATUS_META.sent; const Icon = meta.icon; return <span className={`inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded border ${meta.color}`}><Icon className="h-3 w-3" />{meta.label}</span>; }

export default function Outreach() {
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState("tracker");
  const [trackerFilter, setTrackerFilter] = useState("all");
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedProviderId, setSelectedProviderId] = useState<number | "">("");
  const [selectedTemplateId, setSelectedTemplateId] = useState("service_agreement");
  const [outreachType, setOutreachType] = useState<"email" | "fax">("email");
  const [customSubject, setCustomSubject] = useState("");
  const [customBody, setCustomBody] = useState("");
  const [recipientOverride, setRecipientOverride] = useState("");
  const [copied, setCopied] = useState(false);
  const [uiError, setUiError] = useState<string | null>(null);
  const [customTemplates, setCustomTemplates] = useState<OutreachTemplate[]>([{ id: "custom_kab_followup", name: "KAB / COC Follow-Up", subject: "Follow-Up: KAB / COC Supply Request", body: "Hello {{clinic_name}},\n\nChecking in on the KAB requests, COCs, and specimen supply request we sent to {{clinic_name}} in {{city}}, {{state}}.\n\nPlease let us know the current status and whether you need any changes to the shipment.\n\nThank you,\n[Your Name]" }]);
  const [templateForm, setTemplateForm] = useState({ name: "", subject: "", body: "" });
  const [massSelected, setMassSelected] = useState<Set<number>>(new Set());
  const [massTemplate, setMassTemplate] = useState("service_agreement");
  const [massType, setMassType] = useState<"email" | "fax" | "agreement">("agreement");
  const [massRecording, setMassRecording] = useState(false);

  const { data: records, isLoading: loadingRecords } = useQuery<OutreachRecord[]>({ queryKey: ["/api/outreach"], queryFn: () => customFetch("/api/outreach") });
  const { data: stats } = useQuery<OutreachStats>({ queryKey: ["/api/outreach/stats"], queryFn: () => customFetch("/api/outreach/stats") });
  const { data: providers, isLoading: loadingProviders } = useQuery<OutreachProvider[]>({ queryKey: ["/api/outreach/providers-for-outreach"], queryFn: () => customFetch("/api/outreach/providers-for-outreach") });
  const invalidate = () => { queryClient.invalidateQueries({ queryKey: ["/api/outreach"] }); queryClient.invalidateQueries({ queryKey: ["/api/outreach/stats"] }); };
  const patchMutation = useMutation({ mutationFn: ({ id, data }: { id: number; data: Record<string, unknown> }) => customFetch(`/api/outreach/${id}`, { method: "PATCH", body: JSON.stringify(data) }), onSuccess: () => { invalidate(); setUiError(null); }, onError: (e: Error) => setUiError(e.message || "Failed to update outreach record.") });
  const deleteMutation = useMutation({ mutationFn: (id: number) => customFetch(`/api/outreach/${id}`, { method: "DELETE" }), onSuccess: () => { invalidate(); setUiError(null); }, onError: (e: Error) => setUiError(e.message || "Failed to delete outreach record.") });
  const createMutation = useMutation({ mutationFn: (records: Record<string, unknown>[]) => customFetch("/api/outreach", { method: "POST", body: JSON.stringify({ records }) }), onSuccess: () => { invalidate(); setUiError(null); }, onError: (e: Error) => setUiError(e.message || "Failed to record outreach.") });

  const providerRows = list(providers);
  const recordRows = list(records);
  const selectedProvider = useMemo(() => providerRows.find((p) => p.id === selectedProviderId) ?? null, [providerRows, selectedProviderId]);
  const customTemplate = useMemo(() => customTemplates.find((t) => t.id === selectedTemplateId) ?? null, [customTemplates, selectedTemplateId]);
  const selectedTemplate = useMemo(() => TEMPLATES.find((t) => t.id === selectedTemplateId) ?? TEMPLATES[0], [selectedTemplateId]);
  const generatedSubject = useMemo(() => selectedProvider ? (customTemplate ? applyTemplate(customTemplate, selectedProvider).subject : selectedTemplate.subject(selectedProvider)) : "", [selectedProvider, selectedTemplate, customTemplate]);
  const generatedBody = useMemo(() => selectedProvider ? (customTemplate ? applyTemplate(customTemplate, selectedProvider).body : selectedTemplate.body(selectedProvider)) : "", [selectedProvider, selectedTemplate, customTemplate]);
  const displaySubject = customSubject || generatedSubject;
  const displayBody = customBody || generatedBody;
  const filteredRecords = useMemo(() => { const q = searchTerm.trim().toLowerCase(); return recordRows.filter((r) => { if (trackerFilter === "pending" && r.status !== "sent") return false; if (trackerFilter === "overdue" && !isOverdue(r)) return false; if (trackerFilter === "received" && !(r.status === "received" || r.status === "signed")) return false; if (trackerFilter === "follow_up" && r.status !== "follow_up_needed") return false; return !q || [r.providerName, r.providerState, r.providerCity, r.subject, r.templateName, r.status, r.notes].some((v) => safeText(v).toLowerCase().includes(q)); }); }, [recordRows, trackerFilter, searchTerm]);

  const handleCopy = async () => { try { await navigator.clipboard.writeText(`Subject: ${displaySubject}\n\n${displayBody}`); setCopied(true); setUiError(null); setTimeout(() => setCopied(false), 2000); } catch { setUiError("Could not copy outreach text to clipboard."); } };
  const handleRecordAsSent = async () => { if (!selectedProvider) return; const recipient = requiredRecipient(selectedProvider, outreachType, recipientOverride); if (!recipient) { setUiError(`Cannot record ${outreachType} outreach without a ${outreachType === "email" ? "recipient email" : "fax number"}.`); return; } await createMutation.mutateAsync([{ providerId: selectedProvider.id, providerName: safeText(selectedProvider.clinicName, "Unknown Provider"), providerCity: selectedProvider.city, providerState: selectedProvider.state, providerEmail: selectedProvider.email, providerFax: selectedProvider.fax, outreachType, templateName: customTemplate?.name || selectedTemplate.name, subject: displaySubject, body: displayBody, recipientEmail: outreachType === "email" ? recipient : undefined, recipientFax: outreachType === "fax" ? recipient : undefined, status: "sent" }]); setActiveTab("tracker"); };
  const handleMassRecord = async () => { if (massSelected.size === 0) return; setMassRecording(true); try { const chosenCustom = customTemplates.find((t) => t.id === massTemplate); const chosenTemplate = TEMPLATES.find((t) => t.id === massTemplate) ?? TEMPLATES[0]; const selectedProviders = providerRows.filter((p) => massSelected.has(p.id)); const eligible = selectedProviders.filter((p) => requiredRecipient(p, massType)); if (!eligible.length) { setUiError(`No selected providers have the required ${massType === "fax" ? "fax number" : "email"}.`); return; } const rows = eligible.map((p) => { const rendered = chosenCustom ? applyTemplate(chosenCustom, p) : { subject: chosenTemplate.subject(p), body: chosenTemplate.body(p) }; return { providerId: p.id, providerName: safeText(p.clinicName, "Unknown Provider"), providerCity: p.city, providerState: p.state, providerEmail: p.email, providerFax: p.fax, outreachType: massType, templateName: chosenCustom?.name || chosenTemplate.name, subject: rendered.subject, body: rendered.body, recipientEmail: massType === "fax" ? undefined : p.email, recipientFax: massType === "fax" ? p.fax : undefined, status: "sent" }; }); await createMutation.mutateAsync(rows); setMassSelected(new Set()); setActiveTab("tracker"); } finally { setMassRecording(false); } };
  const addTemplate = () => { if (!templateForm.name || !templateForm.subject || !templateForm.body) { setUiError("Template name, subject, and body are required."); return; } setCustomTemplates((prev) => [{ id: `custom_${Date.now()}`, ...templateForm }, ...prev]); setTemplateForm({ name: "", subject: "", body: "" }); setUiError(null); };

  return <div className="space-y-6 pb-12"><div><h1 className="text-3xl font-bold tracking-tight text-white">Outreach</h1><p className="text-muted-foreground mt-2 text-sm max-w-2xl">Generate outreach text, record provider contact attempts, and track agreement follow-up status.</p></div>{uiError && <div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300 flex gap-2"><AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />{uiError}</div>}<div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Metric label="Total" value={n(stats?.total)} /><Metric label="Sent" value={n(stats?.sent)} /><Metric label="Received" value={n(stats?.received)} green /><Metric label="Signed" value={n(stats?.signed)} green /><Metric label="Overdue" value={n(stats?.overdue)} red /></div>
    <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-5"><TabsList className="bg-black/40 border border-white/[0.08] p-1 rounded-xl"><TabsTrigger value="tracker">Tracker</TabsTrigger><TabsTrigger value="compose">Compose</TabsTrigger><TabsTrigger value="mass">Mass Record</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger></TabsList>
      <TabsContent value="tracker" className="space-y-4"><div className="flex flex-col md:flex-row gap-3"><Input placeholder="Search tracker…" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="bg-black/40 border-white/10 text-white" /><select value={trackerFilter} onChange={(e) => setTrackerFilter(e.target.value)} className="h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white"><option value="all">All</option><option value="pending">Pending</option><option value="overdue">Overdue</option><option value="received">Received/Signed</option><option value="follow_up">Follow Up</option></select></div>{loadingRecords ? <Skeleton className="h-40 w-full bg-white/5" /> : <div className="space-y-3">{filteredRecords.map((r) => <Card key={r.id} className="glass-panel border-white/[0.06]"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold text-white">{safeText(r.providerName, "Unknown Provider")}</div><div className="text-xs text-muted-foreground flex gap-2 mt-1"><MapPin className="h-3 w-3" />{[r.providerCity, r.providerState].filter(Boolean).join(", ") || "Location not listed"}</div></div><StatusBadge status={r.status} /></div><div className="text-sm text-white/80 mt-3">{safeText(r.subject, "No subject")}</div><div className="flex flex-wrap gap-2 mt-3"><Button size="sm" variant="outline" onClick={() => patchMutation.mutate({ id: r.id, data: { status: "received", receivedAt: new Date().toISOString() } })}>Mark Received</Button><Button size="sm" variant="outline" onClick={() => patchMutation.mutate({ id: r.id, data: { status: "signed", receivedAt: new Date().toISOString() } })}>Mark Signed</Button><Button size="sm" variant="outline" onClick={() => deleteMutation.mutate(r.id)} className="border-red-500/20 text-red-300"><Trash2 className="h-3.5 w-3.5" /></Button></div></CardContent></Card>))}{!filteredRecords.length && <Empty>No outreach records match the current filter.</Empty>}</div>}</TabsContent>
      <TabsContent value="compose" className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Card className="glass-panel border-white/[0.06]"><CardContent className="p-5 space-y-3"><select value={selectedProviderId} onChange={(e) => setSelectedProviderId(e.target.value ? Number(e.target.value) : "")} className="w-full h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white"><option value="">Select provider…</option>{providerRows.map((p) => <option key={p.id} value={p.id}>{safeText(p.clinicName, "Unknown Provider")}</option>)}</select><select value={selectedTemplateId} onChange={(e) => setSelectedTemplateId(e.target.value)} className="w-full h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white">{[...TEMPLATES.map((t) => ({ id: t.id, name: t.name })), ...customTemplates].map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={outreachType} onChange={(e) => setOutreachType(e.target.value as "email" | "fax")} className="w-full h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white"><option value="email">Email</option><option value="fax">Fax</option></select><Input placeholder="Recipient override" value={recipientOverride} onChange={(e) => setRecipientOverride(e.target.value)} className="bg-black/40 border-white/10 text-white" /><Button onClick={handleRecordAsSent} disabled={!selectedProvider || createMutation.isPending} className="w-full bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30"><Send className="h-4 w-4 mr-2" />Record as Sent</Button></CardContent></Card><Card className="glass-panel border-white/[0.06]"><CardContent className="p-5 space-y-3"><Input value={customSubject || generatedSubject} onChange={(e) => setCustomSubject(e.target.value)} className="bg-black/40 border-white/10 text-white" placeholder="Subject" /><Textarea value={customBody || generatedBody} onChange={(e) => setCustomBody(e.target.value)} className="bg-black/40 border-white/10 text-white min-h-[260px]" placeholder="Body" /><Button onClick={handleCopy} variant="outline" className="border-white/10 text-muted-foreground hover:text-white">{copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}Copy Text</Button></CardContent></Card></TabsContent>
      <TabsContent value="mass" className="space-y-4"><Card className="glass-panel border-white/[0.06]"><CardContent className="p-5 space-y-4"><div className="rounded-lg border border-primary/20 bg-primary/10 p-3 text-xs text-primary">Mass recording skips providers without the required email/fax contact method.</div><div className="flex gap-2"><select value={massTemplate} onChange={(e) => setMassTemplate(e.target.value)} className="h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white">{[...TEMPLATES.map((t) => ({ id: t.id, name: t.name })), ...customTemplates].map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={massType} onChange={(e) => setMassType(e.target.value as any)} className="h-10 bg-black/40 border border-white/10 rounded-md px-3 text-white"><option value="agreement">Agreement</option><option value="email">Email</option><option value="fax">Fax</option></select><Button onClick={handleMassRecord} disabled={!massSelected.size || massRecording}>Record Selected</Button></div>{loadingProviders ? <Skeleton className="h-40 w-full bg-white/5" /> : <div className="grid grid-cols-1 md:grid-cols-2 gap-2">{providerRows.slice(0, 50).map((p) => <label key={p.id} className="flex items-center gap-3 rounded-lg border border-white/[0.06] bg-black/30 p-3 text-sm text-white"><input type="checkbox" checked={massSelected.has(p.id)} onChange={(e) => setMassSelected((prev) => { const next = new Set(prev); e.target.checked ? next.add(p.id) : next.delete(p.id); return next; })} />{safeText(p.clinicName, "Unknown Provider")}<span className="ml-auto text-xs text-muted-foreground">{safeText(p.state)}</span></label>)}</div>}</CardContent></Card></TabsContent>
      <TabsContent value="templates" className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-sm text-primary">Custom templates are stored only in this browser session right now. They are not backend-persisted.</div><Card className="glass-panel border-white/[0.06]"><CardContent className="p-5 space-y-3"><Input placeholder="Template name" value={templateForm.name} onChange={(e) => setTemplateForm({ ...templateForm, name: e.target.value })} className="bg-black/40 border-white/10 text-white" /><Input placeholder="Subject" value={templateForm.subject} onChange={(e) => setTemplateForm({ ...templateForm, subject: e.target.value })} className="bg-black/40 border-white/10 text-white" /><Textarea placeholder="Body" value={templateForm.body} onChange={(e) => setTemplateForm({ ...templateForm, body: e.target.value })} className="bg-black/40 border-white/10 text-white" /><Button onClick={addTemplate}><Plus className="h-4 w-4 mr-2" />Add Template</Button></CardContent></Card></TabsContent>
    </Tabs></div>;
}

function Metric({ label, value, green, red }: { label: string; value: number; green?: boolean; red?: boolean }) { return <div className="glass-panel border border-white/[0.06] rounded-xl p-4 text-center"><div className={`text-2xl font-black ${red ? "text-red-400" : green ? "text-lime-300" : "text-primary"}`}>{value}</div><div className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">{label}</div></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-lg border border-dashed border-white/10 bg-white/[0.02] p-6 text-center text-sm text-muted-foreground">{children}</div>; }
