import React from "react";
import { useParams, Link } from "wouter";
import { useGetProvider, getGetProviderQueryKey } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Building2, MapPin, Phone, Globe, Mail, FileText, AlertTriangle, ArrowLeft, ShieldCheck, FileSearch, Fingerprint, Tags, ExternalLink, ShieldAlert, UploadCloud, Search } from "lucide-react";
import { format } from "date-fns";

function safeText(value: unknown, fallback = "Unknown") {
  const text = String(value ?? "").trim();
  return text || fallback;
}

function formatSafeDate(value: unknown) {
  const date = new Date(String(value || ""));
  return Number.isNaN(date.getTime()) ? "Unknown date" : format(date, "MMM d, yyyy");
}

function confidenceRatio(sourceCount: unknown) {
  return Math.min(100, Math.max(0, Number(sourceCount || 0) * 20));
}

function servicesList(value: unknown) {
  return String(value || "").split(",").map((item) => item.trim()).filter(Boolean);
}

export default function ProviderDetail() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const { data: provider, isLoading } = useGetProvider(id, { query: { enabled: Number.isFinite(id) && id > 0, queryKey: getGetProviderQueryKey(id) } });

  if (isLoading) return <div className="space-y-8"><Skeleton className="h-6 w-32 bg-white/5" /><Skeleton className="h-12 w-1/2 bg-white/5" /><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><Skeleton className="h-[500px] lg:col-span-2 bg-white/5 rounded-xl" /><Skeleton className="h-[500px] bg-white/5 rounded-xl" /></div></div>;

  if (!provider) return <div className="p-12 flex flex-col items-center text-center text-muted-foreground"><AlertTriangle className="h-12 w-12 text-primary/60 mb-4 drop-shadow-[0_0_15px_rgba(18,173,165,0.3)]" /><h2 className="text-xl font-bold text-white mb-2 tracking-wide">Provider Not Found</h2><p>The intelligence profile you are looking for does not exist or is not available.</p><Link href="/providers" className="mt-6 text-primary hover:text-primary/80 flex items-center gap-2 font-semibold"><ArrowLeft className="h-4 w-4" /> Return to Database</Link></div>;

  const ratio = confidenceRatio(provider.sourceCount);
  const services = servicesList(provider.servicesOffered);
  const addressLine = [provider.address, provider.city, provider.state, provider.zip].map((v) => safeText(v, "")).filter(Boolean).join(", ") || "Address not verified";

  return (
    <div className="space-y-8 pb-12">
      <div>
        <Link href="/providers" className="inline-flex items-center text-xs font-bold uppercase tracking-widest text-muted-foreground hover:text-primary mb-6 transition-colors bg-white/5 px-3 py-1.5 rounded-full border border-white/10 hover:border-primary/30"><ArrowLeft className="h-3.5 w-3.5 mr-2" /> Back to Database</Link>
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-6"><div className="flex gap-6"><div className="h-20 w-20 rounded-2xl bg-black/60 border border-white/10 shadow-[0_8px_30px_rgba(0,0,0,0.5)] flex items-center justify-center shrink-0 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-transparent opacity-50" /><Building2 className="h-8 w-8 text-primary drop-shadow-[0_0_8px_rgba(18,173,165,0.8)] relative z-10" /></div><div><div className="flex items-center gap-4 mb-2"><h1 className="text-4xl font-bold tracking-tight glow-text text-white">{safeText(provider.clinicName, `Provider #${provider.id}`)}</h1></div><div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground"><VerificationBadge status={provider.verificationStatus} /><span className="flex items-center gap-1.5 bg-white/[0.03] px-2 py-1 rounded-md border border-white/[0.05]"><MapPin className="h-3.5 w-3.5 text-primary/70" /> {addressLine}</span><span className="flex items-center gap-1.5 bg-white/[0.03] px-2 py-1 rounded-md border border-white/[0.05]"><Tags className="h-3.5 w-3.5 text-primary/70" /> {provider.clinicType || "General Clinic"}</span></div></div></div><div className="flex flex-wrap gap-2 shrink-0"><Link href="/evidence" className="inline-flex items-center justify-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-4 py-2 text-sm font-semibold text-primary hover:bg-primary/20 transition-colors"><FileText className="h-4 w-4" /> Evidence Library</Link>{provider.website && <a href={provider.website} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-white hover:border-primary/30 hover:text-primary transition-colors"><Globe className="h-4 w-4" /> Website</a>}</div></div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-8"><Card className="glass-panel border-primary/30 relative overflow-hidden shadow-[0_0_40px_rgba(18,173,165,0.06)] bg-black/40"><div className="absolute top-0 left-0 w-1.5 h-full bg-primary shadow-[0_0_20px_rgba(18,173,165,1)]" /><CardHeader className="pb-4 border-b border-white/[0.05] bg-white/[0.02]"><CardTitle className="text-lg flex items-center justify-between text-white"><span className="flex items-center gap-2"><Fingerprint className="h-5 w-5 text-primary" /> Intelligence Profile</span><div className="flex items-center gap-3"><span className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest">Confidence Score</span><div className="w-24 h-2 bg-white/10 rounded-full overflow-hidden border border-white/5"><div className="h-full bg-primary shadow-[0_0_10px_rgba(18,173,165,1)] transition-all duration-1000" style={{ width: `${ratio}%` }} /></div></div></CardTitle></CardHeader><CardContent className="p-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8"><InfoBlock icon={<FileSearch className="h-3.5 w-3.5 text-primary" />} title="Services Offered">{services.length ? <div className="flex flex-wrap gap-2">{services.map((s, i) => <Badge key={i} variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs font-semibold px-2.5 py-1">{s}</Badge>)}</div> : <div className="text-muted-foreground italic text-sm">Unknown / Not extracted</div>}</InfoBlock><InfoBlock icon={<FileText className="h-3.5 w-3.5 text-primary" />} title="Pricing & Billing Notes"><div className="text-white font-medium text-sm leading-relaxed bg-white/[0.02] p-3 rounded-lg border border-white/[0.05]">{provider.pricingNotes || "No specific pricing or billing notes extracted from source documents."}</div></InfoBlock><InfoBlock icon={<Building2 className="h-3.5 w-3.5 text-primary" />} title="Employer Account Setup"><div className="text-white font-medium text-sm leading-relaxed border-l-2 border-primary/50 pl-3 py-1">{provider.employerAccountClues || "No clues regarding employer account setup processes found."}</div></InfoBlock><InfoBlock icon={<AlertTriangle className="h-3.5 w-3.5 text-primary" />} title="External Form Policy"><div className="text-white font-medium text-sm leading-relaxed border-l-2 border-primary/50 pl-3 py-1">{provider.acceptsOutsideForms || "Policy on accepting outside forms is currently unknown."}</div></InfoBlock></div></CardContent></Card>

      <Card className="glass-panel border-white/[0.05] bg-black/20"><CardHeader className="bg-white/[0.01] border-b border-white/[0.05]"><CardTitle className="text-lg text-white">Structured Data Points</CardTitle><CardDescription className="text-muted-foreground">Raw entities extracted from {provider.sourceCount || 0} source files by the extraction engine</CardDescription></CardHeader><CardContent className="p-6">{provider.extractedFields && provider.extractedFields.length > 0 ? <div className="grid gap-4">{provider.extractedFields.map((field) => <div key={field.id} className="p-4 bg-white/[0.03] hover:bg-white/[0.05] transition-colors rounded-xl border border-white/[0.05] group relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-1 bg-white/10 group-hover:bg-primary/50 transition-colors" /><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div className="flex-1"><div className="flex items-center gap-3 mb-1"><span className="font-bold text-white text-sm tracking-wide">{safeText(field.fieldName, "Field")}</span><ConfidenceBadge level={field.confidenceLevel} /></div><div className="text-primary font-medium text-base mb-3 glow-text">{safeText(field.fieldValue, "No value")}</div>{field.sourceSnippet && <div className="text-xs font-mono text-muted-foreground/80 bg-black/60 p-3 rounded-lg border border-white/5 leading-relaxed relative"><div className="absolute -top-2 left-3 bg-black text-[9px] uppercase font-bold text-muted-foreground px-1 tracking-widest">Source Snippet</div>&quot;{field.sourceSnippet}&quot;</div>}</div></div></div>)}</div> : <div className="text-center py-12 text-muted-foreground flex flex-col items-center justify-center bg-white/[0.01] rounded-xl border border-dashed border-white/10"><Fingerprint className="h-10 w-10 opacity-20 mb-3" /><p className="text-sm font-medium tracking-wide">No structured entities extracted yet.</p><Link href="/upload" className="mt-3 inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-3 py-2 text-sm font-medium text-primary hover:bg-primary/20 transition-colors"><UploadCloud className="h-4 w-4" /> Upload Intake</Link></div>}</CardContent></Card></div>

      <div className="space-y-8"><Card className="glass-panel border-white/[0.05] bg-black/40"><CardHeader className="pb-4 border-b border-white/[0.05]"><CardTitle className="text-base text-white tracking-wide">Contact Directory</CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y divide-white/[0.05]"><ContactRow icon={<Phone className="h-4 w-4 text-primary" />} label="Phone Number" value={provider.phone} large /><ContactRow icon={<FileText className="h-4 w-4 text-primary" />} label="Fax Number" value={provider.fax} large /><ContactRow icon={<Mail className="h-4 w-4 text-primary" />} label="Email Address" value={provider.email} /><div className="p-4 flex items-start gap-4 hover:bg-white/[0.02] transition-colors"><div className="mt-0.5 p-2 bg-white/5 rounded-md border border-white/10"><Globe className="h-4 w-4 text-primary" /></div><div className="min-w-0 flex-1"><div className="text-[10px] uppercase font-bold tracking-widest text-muted-foreground mb-0.5">Website</div><div className={`font-medium truncate ${provider.website ? "text-white" : "text-muted-foreground italic text-sm"}`}>{provider.website ? <a href={provider.website} target="_blank" rel="noreferrer" className="text-primary hover:text-primary/80 hover:underline flex items-center gap-1.5 transition-colors">{provider.website.replace(/^https?:\/\//, "")} <ExternalLink className="h-3 w-3" /></a> : "Unverified"}</div></div></div></div></CardContent></Card>

      <Card className="glass-panel border-white/[0.05] flex flex-col max-h-[500px] bg-black/40"><CardHeader className="pb-4 border-b border-white/[0.05] flex flex-row items-center justify-between"><CardTitle className="text-base text-white tracking-wide">Evidence Chain</CardTitle><Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs font-bold">{provider.sourceCount || 0}</Badge></CardHeader><CardContent className="p-0 overflow-y-auto flex-1 custom-scrollbar">{provider.evidenceFiles && provider.evidenceFiles.length > 0 ? <div className="divide-y divide-white/[0.05]">{provider.evidenceFiles.map((file) => <Link key={file.id} href={`/evidence?file=${file.id}`} className="block group"><div className="p-4 hover:bg-white/[0.04] transition-colors flex items-center justify-between relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-0.5 bg-primary opacity-0 group-hover:opacity-100 transition-opacity" /><div className="flex items-center gap-3 min-w-0 pr-4"><div className="h-10 w-10 rounded-lg bg-black/50 border border-white/10 flex items-center justify-center shrink-0 group-hover:border-primary/30 group-hover:shadow-[0_0_10px_rgba(18,173,165,0.2)] transition-all"><FileText className="h-4 w-4 text-muted-foreground group-hover:text-primary transition-colors" /></div><div className="min-w-0"><p className="text-sm font-semibold text-white truncate group-hover:text-primary/90 transition-colors">{safeText(file.originalFilename, `Evidence #${file.id}`)}</p><p className="text-[10px] uppercase tracking-widest font-bold text-muted-foreground/70 mt-1">{formatSafeDate(file.uploadDate)}</p></div></div><Badge variant="outline" className="text-[9px] uppercase tracking-wider font-bold border-white/10 bg-white/5 shrink-0 text-muted-foreground">{file.category || "GEN"}</Badge></div></Link>)}</div> : <div className="p-8 text-center text-muted-foreground flex flex-col items-center"><FileText className="h-8 w-8 opacity-20 mb-3" /><span className="text-sm font-medium tracking-wide">No evidence linked.</span><Link href="/upload" className="mt-3 inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-3 py-2 text-sm font-medium text-primary hover:bg-primary/20 transition-colors"><UploadCloud className="h-4 w-4" /> Upload Intake</Link></div>}</CardContent></Card></div></div>
    </div>
  );
}

function VerificationBadge({ status }: { status?: string | null }) { const verified = status === "Verified"; return <Badge variant="outline" className={`${verified ? "bg-primary/10 text-primary border-primary/30 shadow-[inset_0_0_10px_rgba(18,173,165,0.1),0_0_10px_rgba(18,173,165,0.2)]" : "bg-white/5 text-muted-foreground border-white/10"} font-bold uppercase tracking-widest text-[10px] px-2.5 py-1`}>{verified ? <ShieldCheck className="h-3 w-3 mr-1.5" /> : <ShieldAlert className="h-3 w-3 mr-1.5" />}{verified ? "Verified Profile" : "Unverified"}</Badge>; }
function ConfidenceBadge({ level }: { level?: string | null }) { const safe = level || "MED"; const cls = safe === "HIGH" ? "bg-primary/10 text-primary border-primary/30" : safe === "MEDIUM" ? "bg-teal-500/10 text-teal-300 border-teal-500/30" : "bg-lime-500/10 text-lime-300 border-lime-500/30"; return <Badge variant="outline" className={`text-[9px] uppercase tracking-widest font-bold border ${cls}`}>Conf: {safe}</Badge>; }
function InfoBlock({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <div><div className="flex items-center gap-2 text-muted-foreground mb-2 uppercase tracking-widest text-[10px] font-bold">{icon} {title}</div>{children}</div>; }
function ContactRow({ icon, label, value, large }: { icon: React.ReactNode; label: string; value?: string | null; large?: boolean }) { return <div className="p-4 flex items-start gap-4 hover:bg-white/[0.02] transition-colors"><div className="mt-0.5 p-2 bg-white/5 rounded-md border border-white/10">{icon}</div><div className="min-w-0"><div className="text-[10px] uppercase font-bold tracking-widest text-muted-foreground mb-0.5">{label}</div><div className={`font-medium truncate ${value ? `text-white ${large ? "text-lg tracking-wide" : ""}` : "text-muted-foreground italic text-sm"}`}>{value || "Unverified"}</div></div></div>; }
