import React, { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, CheckCircle2, Activity, FileText, ExternalLink, BarChart3, Building2, Phone, Mail, ShieldCheck, Info, Target, TrendingUp, Users } from "lucide-react";

const KNOWN_SERVICES = ["Drug Testing", "DOT Physicals", "Physical Exams", "Chest X-Ray", "Audiometry", "Vision Testing", "Pulmonary Function", "Spirometry", "Stress Testing", "EKG", "Lab Work", "Urine Testing", "Hair Testing", "Breath Alcohol", "MRO Services", "Urgent Care", "Occupational Therapy", "Workers Comp", "Pre-Employment"];
const US_STATES = ["AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VA","VT","WA","WI","WV","WY"];
const DEPARTMENTS = ["Scheduling", "Finance", "HR", "Operations", "Executive", "Legal", "Clinical", "Other"];
const PRIMARY = "#12ada5";

const TIER_CONFIG: Record<string, { color: string; bg: string; border: string; label: string; icon: React.ElementType; desc: string }> = {
  Critical: { color: "#ef4444", bg: "rgba(239,68,68,0.08)", border: "rgba(239,68,68,0.3)", label: "Critical Difficulty", icon: AlertTriangle, desc: "Extremely difficult — escalate immediately and budget 2–3× standard lead time." },
  Hard: { color: "#fb7185", bg: "rgba(251,113,133,0.08)", border: "rgba(251,113,133,0.3)", label: "High Difficulty", icon: TrendingUp, desc: "Significant challenges. Activate alternate fulfillment strategies in parallel." },
  Moderate: { color: "#14b8a6", bg: "rgba(20,184,166,0.08)", border: "rgba(20,184,166,0.3)", label: "Moderate Difficulty", icon: Target, desc: "Some gaps but manageable with focused effort. Allow extra lead time." },
  Easy: { color: "#84cc16", bg: "rgba(132,204,22,0.08)", border: "rgba(132,204,22,0.3)", label: "Easy / Low Difficulty", icon: CheckCircle2, desc: "Good coverage for this area. Standard outreach should be sufficient." },
};
const CAT_COLORS: Record<string, string> = { Availability: "#14b8a6", Reliability: "#12ada5", Billing: "#84cc16", Accessibility: "#06b6d4", Relationship: "#2dd4bf" };

type Factor = { name?: string; category?: string; points?: number; maxPoints?: number; detail?: string; description?: string };
type Provider = { id: number; clinicName?: string; clinicType?: string | null; city?: string | null; state?: string | null; phone?: string | null; email?: string | null; verificationStatus?: string; tpaFriendly?: boolean; servicesOffered?: string | null; sourceCount?: string | number };
type DifficultyReport = { request?: { state?: string; city?: string | null; service?: string | null; requestedBy?: string | null; department?: string | null; notes?: string | null }; score?: number; tier?: string; totalProviders?: number; verifiedProviders?: number; flaggedProviders?: number; tpaProviders?: number; usableProviders?: number; serviceMatch?: number | null; factors?: Factor[]; providers?: Provider[]; outreachSummary?: { total?: number; failed?: number; agreements?: number; responded?: number }; recommendations?: string[]; generatedAt?: string };

function n(value: unknown) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function clamp(value: unknown, min = 0, max = 100) { return Math.min(max, Math.max(min, n(value))); }
function safeText(value: unknown, fallback = "Not listed") { const text = String(value ?? "").trim(); return text || fallback; }
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }
function safeTier(value: unknown) { const tier = safeText(value, "Moderate"); return TIER_CONFIG[tier] ? tier : "Moderate"; }

function ScoreGauge({ score, tier }: { score: number; tier: string }) {
  const safeScore = clamp(score);
  const arcLen = Math.PI * 80;
  const filled = (safeScore / 100) * arcLen;
  const cfg = TIER_CONFIG[safeTier(tier)] || TIER_CONFIG.Moderate;
  return <svg viewBox="0 0 200 115" className="w-full max-w-[260px] mx-auto block"><path d="M 20 100 A 80 80 0 0 1 180 100" fill="none" stroke="rgba(255,255,255,0.07)" strokeWidth="18" strokeLinecap="round" /><path d="M 20 100 A 80 80 0 0 1 180 100" fill="none" stroke={cfg.color} strokeWidth="18" strokeLinecap="round" strokeDasharray={`${filled.toFixed(1)} ${arcLen.toFixed(1)}`} style={{ transition: "stroke-dasharray 1.6s cubic-bezier(0.4,0,0.2,1), stroke 0.4s" }} /><text x="100" y="82" textAnchor="middle" fill={cfg.color} fontSize="48" fontWeight="900" fontFamily="-apple-system,sans-serif">{Math.round(safeScore)}</text><text x="100" y="103" textAnchor="middle" fill="rgba(255,255,255,0.3)" fontSize="10" fontWeight="700" fontFamily="-apple-system,sans-serif" letterSpacing="1">OUT OF 100</text></svg>;
}

function FactorCard({ factor }: { factor: Factor }) {
  const [tip, setTip] = useState(false);
  const max = Math.max(n(factor.maxPoints), 1);
  const points = clamp(factor.points, 0, max);
  const pct = clamp((points / max) * 100);
  const barColor = pct >= 70 ? "#ef4444" : pct >= 40 ? "#14b8a6" : pct > 0 ? "#2dd4bf" : "#84cc16";
  const catColor = CAT_COLORS[safeText(factor.category)] || PRIMARY;
  return <div className="glass-panel border border-white/[0.06] rounded-xl p-4 space-y-2.5 relative"><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2 min-w-0"><span className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: catColor }} /><span className="text-xs font-bold text-white leading-tight">{safeText(factor.name, "Unnamed factor")}</span></div><div className="flex items-center gap-1.5 flex-shrink-0"><span className="text-xs" style={{ color: barColor, fontWeight: 800 }}>{points}</span><span className="text-[10px] text-muted-foreground">/{max}</span><button onClick={() => setTip((v) => !v)} className="text-muted-foreground/50 hover:text-muted-foreground transition-colors ml-0.5"><Info className="h-3 w-3" /></button></div></div><div className="w-full h-1.5 rounded-full bg-white/[0.07] overflow-hidden"><div className="h-full rounded-full transition-all duration-1000" style={{ width: `${pct}%`, background: barColor, boxShadow: pct > 0 ? `0 0 6px ${barColor}60` : "none" }} /></div><AnimatePresence>{tip && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="text-[10px] text-muted-foreground leading-relaxed overflow-hidden">{safeText(factor.description, "No factor description provided.")}</motion.div>}</AnimatePresence><div className="flex items-center justify-between gap-2"><span className="text-[10px] text-muted-foreground leading-tight flex-1">{safeText(factor.detail, "No detail provided.")}</span><span className="text-[9px] font-bold px-1.5 py-0.5 rounded" style={{ color: catColor, background: `${catColor}15`, border: `1px solid ${catColor}30` }}>{safeText(factor.category, "General")}</span></div></div>;
}

const inputCls = "h-10 bg-black/40 border-white/10 text-white text-sm placeholder:text-muted-foreground/50 focus:border-primary/40 focus:ring-1 focus:ring-primary/20 rounded-lg";
const selectCls = "w-full h-10 rounded-lg bg-black/40 border border-white/10 text-sm text-white px-3 focus:outline-none focus:ring-1 focus:ring-primary/30";

export default function ProviderDifficulty() {
  const [form, setForm] = useState({ state: "", city: "", service: "", requestedBy: "", department: "", notes: "" });
  const [data, setData] = useState<DifficultyReport | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [gaugeScore, setGaugeScore] = useState(0);

  useEffect(() => { if (data) { const t = setTimeout(() => setGaugeScore(clamp(data.score)), 200); return () => clearTimeout(t); } setGaugeScore(0); }, [data]);
  const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((f) => ({ ...f, [k]: e.target.value }));
  const params = () => { const p = new URLSearchParams({ state: form.state }); if (form.city) p.set("city", form.city); if (form.service) p.set("service", form.service); if (form.requestedBy) p.set("requestedBy", form.requestedBy); if (form.department) p.set("department", form.department); if (form.notes) p.set("notes", form.notes); return p; };
  const handleAnalyze = async () => { if (!form.state) { setError("State is required."); return; } setIsAnalyzing(true); setError(null); setData(null); try { const res = await fetch(`/api/analytics/difficulty-report?${params().toString()}`); const json = await res.json().catch(() => null); if (!res.ok) throw new Error(json?.error || `Report request failed with status ${res.status}.`); if (json?.error) throw new Error(json.error); setData(json || {}); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Failed to generate report."); } finally { setIsAnalyzing(false); } };
  const handlePrint = () => { if (!data || !form.state) return; window.open(`/api/analytics/difficulty-report/print?${params().toString()}`, "_blank"); };
  const tierName = safeTier(data?.tier);
  const tier = TIER_CONFIG[tierName] || TIER_CONFIG.Moderate;
  const TierIcon = tier.icon;

  return <div className="space-y-6 pb-12"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="flex items-center gap-3 mb-1"><div className="flex items-center justify-center w-9 h-9 rounded-xl bg-primary/10 border border-primary/20"><BarChart3 className="h-4 w-4 text-primary" /></div><h1 className="text-2xl font-bold text-white tracking-tight">Provider Finder Difficulty Score</h1></div><p className="text-sm text-muted-foreground ml-12">10-factor analysis — generate a scored assessment to justify search complexity to Scheduling or Finance.</p></div>{data && <Button onClick={handlePrint} variant="outline" className="border-white/10 text-white hover:bg-white/[0.06] hover:border-primary/30 gap-2 flex-shrink-0"><FileText className="h-4 w-4 text-primary" />Open Printable Report<ExternalLink className="h-3 w-3 opacity-50" /></Button>}</div>
    <Card className="glass-panel border-white/[0.06]"><CardHeader className="border-b border-white/[0.05] pb-4"><CardTitle className="text-base text-white flex items-center gap-2"><Target className="h-4 w-4 text-primary" />Provider Search Request</CardTitle><CardDescription className="text-xs text-muted-foreground mt-1">Enter the request details — the more specific, the more accurate the difficulty score.</CardDescription></CardHeader><CardContent className="p-6 space-y-5"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="State" required><select className={selectCls} value={form.state} onChange={set("state")}><option value="">Select State…</option>{US_STATES.map((s) => <option key={s} value={s}>{s}</option>)}</select></Field><Field label="City / Metro"><Input className={inputCls} placeholder="e.g. Houston" value={form.city} onChange={set("city")} /></Field><Field label="Service"><select className={selectCls} value={form.service} onChange={set("service")}><option value="">Any service…</option>{KNOWN_SERVICES.map((s) => <option key={s} value={s}>{s}</option>)}</select></Field><Field label="Requested By"><Input className={inputCls} value={form.requestedBy} onChange={set("requestedBy")} placeholder="Name" /></Field><Field label="Department"><select className={selectCls} value={form.department} onChange={set("department")}><option value="">Select department…</option>{DEPARTMENTS.map((d) => <option key={d} value={d}>{d}</option>)}</select></Field><Field label="Notes"><Input className={inputCls} value={form.notes} onChange={set("notes")} placeholder="Optional context" /></Field></div><div className="flex items-center gap-3"><Button onClick={handleAnalyze} disabled={isAnalyzing || !form.state} className="bg-primary/20 hover:bg-primary/30 text-primary border border-primary/30 font-bold">{isAnalyzing ? <><Activity className="h-4 w-4 mr-2 animate-spin" />Analyzing…</> : <><ZapIcon />Generate Difficulty Score</>}</Button>{error && <div className="text-sm text-red-300 bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-2">{error}</div>}</div></CardContent></Card>
    <AnimatePresence>{data && <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 16 }} className="space-y-5"><Card className="glass-panel border-white/[0.06]"><CardContent className="p-6 grid grid-cols-1 lg:grid-cols-3 gap-6 items-center"><div><ScoreGauge score={gaugeScore} tier={tierName} /></div><div className="lg:col-span-2 space-y-4"><div className="rounded-xl border p-4" style={{ background: tier.bg, borderColor: tier.border }}><div className="flex items-center gap-2 text-xl font-black" style={{ color: tier.color }}><TierIcon className="h-5 w-5" />{tier.label}</div><div className="text-sm text-muted-foreground mt-2">{tier.desc}</div></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Metric label="Total" value={n(data.totalProviders)} /><Metric label="Verified" value={n(data.verifiedProviders)} green /><Metric label="TPA" value={n(data.tpaProviders)} /><Metric label="Usable" value={n(data.usableProviders)} green /><Metric label="Flagged" value={n(data.flaggedProviders)} red /></div></div></CardContent></Card>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Card className="glass-panel border-white/[0.06]"><CardHeader className="border-b border-white/[0.05] pb-4"><CardTitle className="text-base text-white flex items-center gap-2"><BarChart3 className="h-4 w-4 text-primary" />Scoring Factors</CardTitle></CardHeader><CardContent className="p-5 grid grid-cols-1 md:grid-cols-2 gap-3">{list(data.factors).length ? list(data.factors).map((f, i) => <FactorCard key={`${safeText(f.name, "factor")}-${i}`} factor={f} />) : <Empty>No scoring factors returned.</Empty>}</CardContent></Card><Card className="glass-panel border-white/[0.06]"><CardHeader className="border-b border-white/[0.05] pb-4"><CardTitle className="text-base text-white flex items-center gap-2"><Building2 className="h-4 w-4 text-primary" />Matched Providers</CardTitle></CardHeader><CardContent className="p-5 space-y-3 max-h-[520px] overflow-y-auto custom-scrollbar">{list(data.providers).length ? list(data.providers).map((p) => <ProviderRow key={p.id} p={p} />) : <Empty>No matching providers returned.</Empty>}</CardContent></Card></div>
      <Card className="glass-panel border-white/[0.06]"><CardHeader className="border-b border-white/[0.05] pb-4"><CardTitle className="text-base text-white flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" />Recommendations</CardTitle></CardHeader><CardContent className="p-5 space-y-2">{list(data.recommendations).length ? list(data.recommendations).map((r, i) => <div key={i} className="rounded-lg border border-white/[0.06] bg-white/[0.03] p-3 text-sm text-white leading-relaxed">{safeText(r)}</div>) : <Empty>No recommendations returned.</Empty>}</CardContent></Card></motion.div>}</AnimatePresence></div>;
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <div className="space-y-1.5"><label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">{label} {required && <span className="text-red-400">*</span>}</label>{children}</div>; }
function Metric({ label, value, green, red }: { label: string; value: number; green?: boolean; red?: boolean }) { return <div className="rounded-xl border border-white/[0.06] bg-white/[0.03] p-3 text-center"><div className={`text-2xl font-black ${red ? "text-red-400" : green ? "text-lime-300" : "text-primary"}`}>{value}</div><div className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">{label}</div></div>; }
function ProviderRow({ p }: { p: Provider }) { return <div className="rounded-xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold text-white">{safeText(p.clinicName, "Unknown Provider")}</div><div className="text-xs text-muted-foreground">{[p.city, p.state].filter(Boolean).join(", ") || "Location not listed"}</div></div>{p.verificationStatus === "Verified" && <ShieldCheck className="h-4 w-4 text-lime-300" />}</div><div className="flex flex-wrap gap-3 mt-3 text-xs text-muted-foreground">{p.phone && <span className="flex items-center gap-1"><Phone className="h-3 w-3" />{p.phone}</span>}{p.email && <span className="flex items-center gap-1"><Mail className="h-3 w-3" />{p.email}</span>}{p.tpaFriendly && <span className="text-lime-300">Corporate billing clue</span>}</div></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-lg border border-dashed border-white/10 bg-white/[0.02] p-4 text-center text-sm text-muted-foreground col-span-full">{children}</div>; }
function ZapIcon() { return <span className="inline-flex mr-2"><BarChart3 className="h-4 w-4" /></span>; }
