import React from "react";
import { useParams, Link } from "wouter";
import { useGetProvider, getGetProviderQueryKey } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Building2, MapPin, Phone, Globe, Mail, FileText, AlertTriangle, ArrowLeft, ShieldCheck, FileSearch, Fingerprint, Tags, ExternalLink, ShieldAlert, UploadCloud, Send, MessageSquare, ListChecks } from "lucide-react";
import { format } from "date-fns";

function safeText(value: unknown, fallback = "Unknown") { const text = String(value ?? "").trim(); return text || fallback; }
function n(value: unknown) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }
function formatSafeDate(value: unknown) { const date = new Date(String(value || "")); return Number.isNaN(date.getTime()) ? "Unknown date" : format(date, "MMM d, yyyy"); }
function confidenceRatio(sourceCount: unknown) { return Math.min(100, Math.max(0, n(sourceCount) * 20)); }
function servicesList(value: unknown) { return String(value || "").split(",").map((item) => item.trim()).filter(Boolean); }
function normalizeUrl(value: unknown) { const raw = safeText(value, ""); if (!raw) return ""; if (/^https?:\/\//i.test(raw)) return raw; return `https://${raw}`; }

export default function ProviderDetail() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const validId = Number.isFinite(id) && id > 0;
  const { data: provider, isLoading } = useGetProvider(id, { query: { enabled: validId, queryKey: getGetProviderQueryKey(id) } });

  if (!validId) return <EmptyState title="Invalid Provider ID" message="This provider link does not include a valid numeric provider ID." />;
  if (isLoading) return <div className="space-y-8"><Skeleton className="h-6 w-32 bg-white/5" /><Skeleton className="h-12 w-1/2 bg-white/5" /><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><Skeleton className="h-[500px] lg:col-span-2 bg-white/5 rounded-xl" /><Skeleton className="h-[500px] bg-white/5 rounded-xl" /></div></div>;
  if (!provider) return <EmptyState title="Provider Not Found" message="The intelligence profile you are looking for does not exist or is not available." />;

  const ratio = confidenceRatio(provider.sourceCount);
  const services = servicesList(provider.servicesOffered);
  const evidenceFiles = list(provider.evidenceFiles);
  const extractedFields = list(provider.extractedFields);
  const websiteUrl = normalizeUrl(provider.website);
  const addressLine = [provider.address, provider.city, provider.state, provider.zip].map((v) => safeText(v, "")).filter(Boolean).join(", ") || "Address not verified";

  return <div className="space-y-8 pb-12"><div><Link href="/providers" className="inline-flex items-center text-xs font-bold uppercase tracking-widest text-muted-foreground hover:text-primary mb-6 transition-colors bg-white/5 px-3 py-1.5 rounded-full border border-white/10 hover:border-primary/30"><ArrowLeft className="h-3.5 w-3.5 mr-2" /> Back to Database</Link><div className="flex flex-col md:flex-row md:items-start justify-between gap-6"><div className="flex gap-6"><div className="h-20 w-20 rounded-2xl bg-black/60 border border-white/10 shadow-[0_8px_30px_rgba(0,0,0,0.5)] flex items-center justify-center shrink-0 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-transparent opacity-50" /><Building2 className="h-8 w-8 text-primary drop-shadow-[0_0_8px_rgba(18,173,165,0.8)] relative z-10" /></div><div><h1 className="text-4xl font-bold tracking-tight text-white mb-2">{safeText(provider.clinicName, `Provider #${provider.id}`)}</h1><div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground"><VerificationBadge status={provider.verificationStatus} /><span className="flex items-center gap-1.5 bg-white/[0.03] px-2 py-1 rounded-md border border-white/[0.05]"><MapPin className="h-3.5 w-3.5 text-primary/70" /> {addressLine}</span><span className="flex items-center gap-1.5 bg-white/[0.03] px-2 py-1 rounded-md border border-white/[0.05]"><Tags className="h-3.5 w-3.5 text-primary/70" /> {safeText(provider.clinicType, "General Clinic")}</span></div></div></div><div className="flex flex-wrap gap-2 shrink-0"><ActionLink href="/outreach" icon={<Send className="h-4 w-4" />} label="Outreach" primary /><ActionLink href="/secure-comms" icon={<MessageSquare className="h-4 w-4" />} label="Secure Comms" /><ActionLink href="/upload" icon={<UploadCloud className="h-4 w-4" />} label="Upload Evidence" /><ActionLink href="/evidence" icon={<FileText className="h-4 w-4" />} label="Evidence" />{websiteUrl && <a href={websiteUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-white hover:border-primary/30 hover:text-primary transition-colors"><Globe className="h-4 w-4" /> Website</a>}</div></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-8"><Card className="glass-panel border-primary/30 relative overflow-hidden shadow-[0_0_40px_rgba(18,173,165,0.06)] bg-black/40"><div className="absolute top-0 left-0 w-1.5 h-full bg-primary shadow-[0_0_20px_rgba(18,173,165,1)]" /><CardHeader className="pb-4 border-b border-white/[0.05] bg-white/[0.02]"><CardTitle className="text-lg flex items-center justify-between text-white"><span className="flex items-center gap-2"><Fingerprint className="h-5 w-5 text-primary" /> Intelligence Profile</span><div className="flex items-center gap-3"><span className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest">Confidence Score</span><div className="w-24 h-2 bg-white/10 rounded-full overflow-hidden border border-white/5"><div className="h-full bg-primary shadow-[0_0_10px_rgba(18,173,165,1)] transition-all duration-1000" style={{ width: `${ratio}%` }} /></div></div></CardTitle></CardHeader><CardContent className="p-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8"><InfoBlock icon={<FileSearch className="h-3.5 w-3.5 text-primary" />} title="Services Offered">{services.length ? <div className="flex flex-wrap gap-2">{services.map((s, i) => <Badge key={`${s}-${i}`} variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs font-semibold px-2.5 py-1">{s}</Badge>)}</div> : <div className="text-muted-foreground italic text-sm">Unknown / Not extracted</div>}</InfoBlock><InfoBlock icon={<FileText className="h-3.5 w-3.5 text-primary" />} title="Pricing & Billing Notes"><InfoText>{safeText(provider.pricingNotes, "No specific pricing or billing notes extracted from source documents.")}</InfoText></InfoBlock><InfoBlock icon={<Building2 className="h-3.5 w-3.5 text-primary" />} title="Employer Account Setup"><InfoText accent>{safeText(provider.employerAccountClues, "No clues regarding employer account setup processes found.")}</InfoText></InfoBlock><InfoBlock icon={<AlertTriangle className="h-3.5 w-3.5 text-primary" />} title="External Form Policy"><InfoText accent>{safeText(provider.acceptsOutsideForms, "Policy on accepting outside forms is currently unknown.")}</InfoText></InfoBlock></div></CardContent></Card>
      <Card className="glass-panel border-white/[0.05] bg-black/20"><CardHeader className="bg-white/[0.01] border-b border-white/[0.05]"><CardTitle className="text-lg text-white">Structured Data Points</CardTitle><CardDescription className="text-muted-foreground">Raw entities extracted from {n(provider.sourceCount)} source files by the extraction engine</CardDescription></CardHeader><CardContent className="p-6">{extractedFields.length ? <div className="grid gap-4">{extractedFields.map((field: any, i) => <div key={field.id || i} className="p-4 bg-white/[0.03] hover:bg-white/[0.05] transition-colors rounded-xl border border-white/[0.05] group relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-1 bg-white/10 group-hover:bg-primary/50 transition-colors" /><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div className="flex-1"><div className="flex items-center gap-3 mb-1"><span className="font-bold text-white text-sm tracking-wide">{safeText(field.fieldName, "Field")}</span><ConfidenceBadge level={field.confidenceLevel} /></div><div className="text-primary font-medium text-base mb-3">{safeText(field.fieldValue, "No value")}</div>{field.sourceSnippet && <div className="text-xs font-mono text-muted-foreground/80 bg-black/60 p-3 rounded-lg border border-white/5 leading-relaxed relative"><div className="absolute -top-2 left-3 bg-black text-[9px] uppercase font-bold text-muted-foreground px-1 tracking-widest">Source Snippet</div>&quot;{safeText(field.sourceSnippet)}&quot;</div>}</div></div></div>)}</div> : <NoData icon={<Fingerprint className="h-10 w-10 opacity-20 mb-3" />} text="No structured entities extracted yet." link="/upload" linkText="Upload Intake" />}</CardContent></Card></div>
      <div className="space-y-8"><Card className="glass-panel border-white/[0.05] bg-black/40"><CardHeader className="pb-4 border-b border-white/[0.05]"><CardTitle className="text-base text-white tracking-wide">Contact Directory</CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y divide-white/[0.05]"><ContactRow icon={<Phone className="h-4 w-4 text-primary" />} label="Phone Number" value={provider.phone} large /><ContactRow icon={<FileText className="h-4 w-4 text-primary" />} label="Fax Number" value={provider.fax} large /><ContactRow icon={<Mail className="h-4 w-4 text-primary" />} label="Email Address" value={provider.email} /><ContactRow icon={<Globe className="h-4 w-4 text-primary" />} label="Website" value={websiteUrl ? websiteUrl.replace(/^https?:\/\//, "") : ""} href={websiteUrl} /></div></CardContent></Card>
      <Card className="glass-panel border-white/[0.05] flex flex-col max-h-[500px] bg-black/40"><CardHeader className="pb-4 border-b border-white/[0.05] flex flex-row items-center justify-between"><CardTitle className="text-base text-white tracking-wide">Evidence Chain</CardTitle><Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs font-bold">{n(provider.sourceCount)}</Badge></CardHeader><CardContent className="p-0 overflow-y-auto flex-1 custom-scrollbar">{evidenceFiles.length ? <div className="divide-y divide-white/[0.05]">{evidenceFiles.map((file: any, i) => <Link key={file.id || i} href={`/evidence?file=${file.id}`} className="block group"><div className="p-4 hover:bg-white/[0.04] transition-colors flex items-center justify-between relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-0.5 bg-primary opacity-0 group-hover:opacity-100 transition-opacity" /><div className="flex items-center gap-3 min-w-0 pr-4"><div className="h-10 w-10 rounded-lg bg-black/50 border border-white/10 flex items-center justify-center shrink-0 group-hover:border-primary/30 group-hover:shadow-[0_0_10px_rgba(18,173,165,0.2)] transition-all"><FileText className="h-4 w-4 text-muted-foreground group-hover:text-primary transition-colors" /></div><div className="min-w-0"><p className="text-sm font-semibold text-white truncate group-hover:text-primary/90 transition-colors">{safeText(file.originalFilename, `Evidence #${safeText(file.id, i + 1)}`)}</p><p className="text-[10px] uppercase tracking-widest font-bold text-muted-foreground/70 mt-1">{formatSafeDate(file.uploadDate)}</p></div></div><Badge variant="outline" className="text-[9px] uppercase tracking-wider font-bold border-white/10 bg-white/5 shrink-0 text-muted-foreground">{safeText(file.category, "GEN")}</Badge></div></Link>)}</div> : <NoData icon={<FileText className="h-8 w-8 opacity-20 mb-3" />} text="No evidence linked." link="/upload" linkText="Upload Intake" />}</CardContent></Card></div></div></div>;
}
function EmptyState({ title, message }: { title: string; message: string }) { return <div className="p-12 flex flex-col items-center text-center text-muted-foreground"><AlertTriangle className="h-12 w-12 text-primary/60 mb-4 drop-shadow-[0_0_15px_rgba(18,173,165,0.3)]" /><h2 className="text-xl font-bold text-white mb-2 tracking-wide">{title}</h2><p>{message}</p><Link href="/providers" className="mt-6 text-primary hover:text-primary/80 flex items-center gap-2 font-semibold"><ArrowLeft className="h-4 w-4" /> Return to Database</Link></div>; }
function ActionLink({ href, icon, label, primary }: { href: string; icon: React.ReactNode; label: string; primary?: boolean }) { return <Link href={href} className={`inline-flex items-center justify-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold transition-colors ${primary ? "border-primary/30 bg-primary/10 text-primary hover:bg-primary/20" : "border-white/10 bg-white/[0.04] text-white hover:border-primary/30 hover:text-primary"}`}>{icon}{label}</Link>; }
function VerificationBadge({ status }: { status?: string | null }) { const verified = status === "Verified"; return <Badge variant="outline" className={`${verified ? "bg-primary/10 text-primary border-primary/30 shadow-[inset_0_0_10px_rgba(18,173,165,0.1),0_0_10px_rgba(18,173,165,0.2)]" : "bg-white/5 text-muted-foreground border-white/10"} font-bold uppercase tracking-widest text-[10px] px-2.5 py-1`}>{verified ? <ShieldCheck className="h-3 w-3 mr-1.5" /> : <ShieldAlert className="h-3 w-3 mr-1.5" />}{verified ? "Verified Profile" : "Unverified"}</Badge>; }
function ConfidenceBadge({ level }: { level?: string | null }) { const safe = safeText(level, "MED").toUpperCase(); const cls = safe === "HIGH" ? "bg-primary/10 text-primary border-primary/30" : safe === "LOW" ? "bg-red-500/10 text-red-300 border-red-500/30" : "bg-white/10 text-muted-foreground border-white/20"; return <Badge variant="outline" className={`${cls} text-[9px] font-bold uppercase tracking-wider`}>{safe}</Badge>; }
function InfoBlock({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <div><div className="flex items-center gap-2 text-[10px] uppercase font-bold tracking-widest text-muted-foreground mb-3">{icon}{title}</div>{children}</div>; }
function InfoText({ children, accent }: { children: React.ReactNode; accent?: boolean }) { return <div className={`text-white font-medium text-sm leading-relaxed ${accent ? "border-l-2 border-primary/50 pl-3 py-1" : "bg-white/[0.02] p-3 rounded-lg border border-white/[0.05]"}`}>{children}</div>; }
function ContactRow({ icon, label, value, large, href }: { icon: React.ReactNode; label: string; value?: unknown; large?: boolean; href?: string }) { const text = safeText(value, ""); return <div className="p-4 flex items-start gap-4 hover:bg-white/[0.02] transition-colors"><div className="mt-0.5 p-2 bg-white/5 rounded-md border border-white/10">{icon}</div><div className="min-w-0 flex-1"><div className="text-[10px] uppercase font-bold tracking-widest text-muted-foreground mb-0.5">{label}</div><div className={`${large ? "text-lg font-semibold" : "font-medium"} truncate ${text ? "text-white" : "text-muted-foreground italic text-sm"}`}>{href && text ? <a href={href} target="_blank" rel="noreferrer" className="text-primary hover:text-primary/80 hover:underline inline-flex items-center gap-1.5">{text}<ExternalLink className="h-3 w-3" /></a> : text || "Unverified"}</div></div></div>; }
function NoData({ icon, text, link, linkText }: { icon: React.ReactNode; text: string; link: string; linkText: string }) { return <div className="p-8 text-center text-muted-foreground flex flex-col items-center">{icon}<span className="text-sm font-medium tracking-wide">{text}</span><Link href={link} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-3 py-2 text-sm font-medium text-primary hover:bg-primary/20 transition-colors"><UploadCloud className="h-4 w-4" /> {linkText}</Link></div>; }
