import React, { useCallback, useRef, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { motion, AnimatePresence } from "framer-motion";
import { customFetch } from "@workspace/api-client-react";
import { UploadCloud, FileSpreadsheet, RefreshCw, AlertTriangle, CheckCircle2, MapPin, Building2, Search, ArrowUpDown, Download, Activity, ShieldCheck } from "lucide-react";

const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;

type ParsedResult = { headers?: string[]; totalRows?: number; detected?: { state?: number | null; city?: number | null; date?: number | null; notes?: number | null; name?: number | null }; preview?: Record<string, string>[]; rows?: Array<{ state?: string; city?: string | null; date?: string | null; notes?: string | null; name?: string | null }> };
type LocationRow = { state?: string; city?: string | null; attempts?: number; providers?: number; verifiedProviders?: number; outreachAttempts?: number; gapScore?: string };
type StateSummaryRow = { state?: string; totalAttempts?: number; providers?: number; verifiedProviders?: number; outreachAttempts?: number };
type AnalysisResult = { locations?: LocationRow[]; stateSummary?: StateSummaryRow[]; totalRows?: number; uniqueStates?: number; uniqueLocations?: number };

const GAP_CONFIG: Record<string, { color: string; bg: string; border: string }> = {
  Critical: { color: "#ef4444", bg: "rgba(239,68,68,0.1)", border: "rgba(239,68,68,0.3)" },
  High: { color: "#fb7185", bg: "rgba(251,113,133,0.1)", border: "rgba(251,113,133,0.3)" },
  Medium: { color: "#14b8a6", bg: "rgba(20,184,166,0.1)", border: "rgba(20,184,166,0.3)" },
  Low: { color: "#84cc16", bg: "rgba(132,204,22,0.1)", border: "rgba(132,204,22,0.3)" },
};

function safeText(value: unknown, fallback = "") { const text = String(value ?? "").trim(); return text || fallback; }
function n(value: unknown) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }
function csvEscape(value: unknown) { const text = String(value ?? ""); return /[",\n\r]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function fileValidationError(file: File) { const ext = file.name.split(".").pop()?.toLowerCase(); if (!file.size) return "The selected file is empty."; if (file.size > MAX_UPLOAD_BYTES) return "File is too large. Maximum upload size is 25 MB."; if (!["csv", "xlsx", "xls"].includes(ext ?? "")) return "Please upload a CSV, XLSX, or XLS file."; return null; }

function ColMapSelect({ label, value, options, onChange }: { label: string; value: number | null; options: string[]; onChange: (v: number | null) => void }) {
  return <div className="space-y-1.5"><label className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">{label}</label><select className="w-full h-9 bg-black/40 border border-white/10 text-white text-sm rounded-lg px-3 focus:outline-none focus:ring-1 focus:ring-primary/30" value={value ?? ""} onChange={(e) => onChange(e.target.value === "" ? null : Number(e.target.value))}><option value="">— not mapped —</option>{options.map((h, i) => <option key={i} value={i}>{safeText(h, `Column ${i + 1}`)}</option>)}</select></div>;
}

export default function SearchMapping() {
  const [stage, setStage] = useState<"upload" | "mapping" | "analyzing" | "results">("upload");
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [parsed, setParsed] = useState<ParsedResult | null>(null);
  const [colMap, setColMap] = useState<{ state: number | null; city: number | null }>({ state: null, city: null });
  const [results, setResults] = useState<AnalysisResult | null>(null);
  const [filterText, setFilterText] = useState("");
  const [sortBy, setSortBy] = useState<"attempts" | "providers" | "gap">("attempts");
  const [activeTab, setActiveTab] = useState<"locations" | "states">("states");
  const fileRef = useRef<HTMLInputElement>(null);

  const uploadFile = useCallback(async (file: File) => {
    const validationError = fileValidationError(file);
    if (validationError) { setError(validationError); return; }
    setIsLoading(true); setError(null);
    try { const fd = new FormData(); fd.append("file", file); const data: ParsedResult = await customFetch("/api/analytics/search-map/parse", { method: "POST", body: fd }); setParsed(data || {}); setColMap({ state: data?.detected?.state ?? null, city: data?.detected?.city ?? null }); setStage("mapping"); }
    catch (e: unknown) { setError(e instanceof Error ? e.message : "Failed to parse file. Please check the format."); }
    finally { setIsLoading(false); }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => { e.preventDefault(); setIsDragging(false); const file = e.dataTransfer.files[0]; if (file) uploadFile(file); }, [uploadFile]);
  const handleAnalyze = async () => { if (!parsed || colMap.state == null) { setError("State column is required before analysis."); return; } setIsLoading(true); setError(null); setStage("analyzing"); try { const rows = list(parsed.rows).map((r) => ({ state: safeText(r.state), city: safeText(r.city) || null })).filter((r) => r.state); const data: AnalysisResult = await customFetch("/api/analytics/search-map/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }); setResults(data || {}); setStage("results"); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Analysis failed."); setStage("mapping"); } finally { setIsLoading(false); } };
  const reset = () => { setStage("upload"); setParsed(null); setResults(null); setError(null); setFilterText(""); setColMap({ state: null, city: null }); };
  const exportCSV = () => { const locations = list(results?.locations); if (!locations.length) return; const headers = ["State", "City", "Attempts", "Providers in DB", "Verified Providers", "Outreach Attempts", "Gap Score"]; const rows = locations.map((l) => [l.state, l.city || "", n(l.attempts), n(l.providers), n(l.verifiedProviders), n(l.outreachAttempts), l.gapScore].map(csvEscape).join(",")); const blob = new Blob([[headers.map(csvEscape).join(","), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `search-location-mapping-${Date.now()}.csv`; a.click(); URL.revokeObjectURL(url); };

  const q = filterText.trim().toLowerCase();
  const filteredLocations = list(results?.locations).filter((l) => !q || [l.state, l.city, l.gapScore].some((v) => safeText(v).toLowerCase().includes(q))).sort((a, b) => { if (sortBy === "attempts") return n(b.attempts) - n(a.attempts); if (sortBy === "providers") return n(b.providers) - n(a.providers); const gapOrder: Record<string, number> = { Critical: 4, High: 3, Medium: 2, Low: 1 }; return (gapOrder[safeText(b.gapScore)] || 0) - (gapOrder[safeText(a.gapScore)] || 0); });
  const filteredStates = list(results?.stateSummary).filter((s) => !q || safeText(s.state).toLowerCase().includes(q));
  const headers = list(parsed?.headers);

  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-black text-white tracking-tight">Search Attempt Mapper</h1><p className="text-sm text-muted-foreground mt-1">Upload CSV or Excel search-request history to map location frequency and cross-reference provider coverage.</p></div>{stage !== "upload" && <Button variant="outline" onClick={reset} className="border-white/10 text-muted-foreground hover:text-white gap-2 flex-shrink-0"><RefreshCw className="h-3.5 w-3.5" />New Upload</Button>}</div>
    <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest">{(["upload", "mapping", "results"] as const).map((s, i) => { const done = (stage === "mapping" && i < 1) || (stage === "results" && i < 2) || (stage === "analyzing" && i < 2); const active = stage === s || (stage === "analyzing" && s === "mapping"); return <React.Fragment key={s}>{i > 0 && <div className={`flex-1 h-px ${done ? "bg-primary/60" : "bg-white/10"}`} />}<div className={`flex items-center gap-1.5 px-3 py-1 rounded-full transition-all ${active ? "bg-primary/15 text-primary border border-primary/30" : done ? "text-primary/60" : "text-muted-foreground/40"}`}>{done ? <CheckCircle2 className="h-3 w-3" /> : <span className="w-3.5 h-3.5 rounded-full border flex items-center justify-center text-[8px]" style={{ borderColor: "currentColor" }}>{i + 1}</span>}{s === "upload" ? "Upload File" : s === "mapping" ? "Map Columns" : "Results"}</div></React.Fragment>; })}</div>
    {error && <div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300 flex items-start gap-2"><AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />{error}</div>}
    <AnimatePresence mode="wait">{stage === "upload" && <motion.div key="upload" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}><div onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }} onDragLeave={() => setIsDragging(false)} onDrop={handleDrop} onClick={() => fileRef.current?.click()} className={`border-2 border-dashed rounded-2xl p-16 text-center cursor-pointer transition-all duration-300 ${isDragging ? "border-primary/70 bg-primary/[0.06]" : "border-white/10 hover:border-white/25 hover:bg-white/[0.02]"}`}><input ref={fileRef} type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadFile(f); e.currentTarget.value = ""; }} />{isLoading ? <div><Activity className="h-10 w-10 text-primary mx-auto mb-4 animate-spin" /><p className="text-sm font-bold text-white">Parsing file…</p></div> : <div><UploadCloud className={`h-12 w-12 mx-auto mb-4 transition-colors ${isDragging ? "text-primary" : "text-muted-foreground/40"}`} /><p className="text-base font-bold text-white mb-1">Drop your file here, or click to browse</p><p className="text-sm text-muted-foreground mb-6">Supports CSV, XLSX, and XLS — up to 25 MB</p><div className="inline-flex items-center gap-3 text-[10px] text-muted-foreground/60"><FileSpreadsheet className="h-3.5 w-3.5" />.csv<FileSpreadsheet className="h-3.5 w-3.5" />.xlsx<FileSpreadsheet className="h-3.5 w-3.5" />.xls</div></div>}</div><Card className="glass-panel border-white/[0.06] mt-4"><CardHeader className="pb-3"><CardTitle className="text-sm text-white">What should my file look like?</CardTitle><CardDescription className="text-xs">The system auto-detects column names. Any spreadsheet with state/location data works.</CardDescription></CardHeader><CardContent className="p-5 pt-0"><div className="overflow-x-auto rounded-lg border border-white/[0.06]"><table className="w-full text-xs"><thead><tr className="bg-white/[0.04]">{["State", "City", "Date Requested", "Employee Name", "Notes"].map((h) => <th key={h} className="px-4 py-2.5 text-left font-bold text-primary">{h}</th>)}</tr></thead><tbody>{[["TX", "Houston", "2026-04-12", "J. Williams", "DOT Physical needed"], ["CA", "Los Angeles", "2026-04-14", "M. Torres", "Pre-employment drug screen"], ["FL", "Miami", "2026-04-18", "K. Davis", "Audiometry test"]].map((row, i) => <tr key={i} className="border-t border-white/[0.04]">{row.map((c) => <td key={c} className="px-4 py-2 text-muted-foreground">{c}</td>)}</tr>)}</tbody></table></div></CardContent></Card></motion.div>}
      {stage === "mapping" && parsed && <motion.div key="mapping" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="space-y-4"><Card className="glass-panel border-white/[0.06]"><CardHeader><CardTitle className="text-white text-base">Confirm Column Mapping</CardTitle><CardDescription className="text-xs">Column selectors show detected fields. Analysis currently uses the parsed state/city rows returned by the backend parser.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="rounded-lg border border-primary/20 bg-primary/10 p-3 text-xs text-primary flex gap-2"><AlertTriangle className="h-3.5 w-3.5 shrink-0 mt-0.5" />Changing these selectors confirms the mapping for review, but remapping depends on backend parser support.</div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><ColMapSelect label="State Column" value={colMap.state} options={headers} onChange={(v) => setColMap((m) => ({ ...m, state: v }))} /><ColMapSelect label="City Column" value={colMap.city} options={headers} onChange={(v) => setColMap((m) => ({ ...m, city: v }))} /></div><div className="text-xs text-muted-foreground">Rows detected: {n(parsed.totalRows)} · Preview rows: {list(parsed.preview).length}</div><Button onClick={handleAnalyze} disabled={isLoading || colMap.state == null} className="bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30">Analyze Coverage</Button></CardContent></Card></motion.div>}
      {stage === "analyzing" && <motion.div key="analyzing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="rounded-2xl border border-white/10 bg-black/30 p-16 text-center"><Activity className="h-10 w-10 text-primary mx-auto mb-4 animate-spin" /><p className="font-bold text-white">Analyzing search locations…</p></motion.div>}
      {stage === "results" && results && <motion.div key="results" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Rows" value={n(results.totalRows)} /><Metric label="States" value={n(results.uniqueStates)} /><Metric label="Locations" value={n(results.uniqueLocations)} /><Metric label="Critical Gaps" value={list(results.locations).filter((l) => l.gapScore === "Critical").length} red /></div><div className="flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><div className="flex gap-2"><Button variant={activeTab === "states" ? "default" : "outline"} onClick={() => setActiveTab("states")}>States</Button><Button variant={activeTab === "locations" ? "default" : "outline"} onClick={() => setActiveTab("locations")}>Locations</Button></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" /><input value={filterText} onChange={(e) => setFilterText(e.target.value)} placeholder="Filter…" className="pl-8 h-9 bg-black/40 border border-white/10 rounded-md text-sm text-white" /></div><select value={sortBy} onChange={(e) => setSortBy(e.target.value as any)} className="h-9 bg-black/40 border border-white/10 rounded-md text-sm text-white px-2"><option value="attempts">Attempts</option><option value="providers">Providers</option><option value="gap">Gap</option></select><Button onClick={exportCSV} variant="outline" className="border-white/10 text-muted-foreground hover:text-white"><Download className="h-4 w-4 mr-2" />CSV</Button></div></div>{activeTab === "states" ? <DataCard rows={filteredStates} type="states" /> : <DataCard rows={filteredLocations} type="locations" />}</motion.div>}
    </AnimatePresence></div>;
}

function Metric({ label, value, red }: { label: string; value: number; red?: boolean }) { return <div className="glass-panel border border-white/[0.06] rounded-xl p-4 text-center"><div className={`text-2xl font-black ${red ? "text-red-400" : "text-primary"}`}>{value}</div><div className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">{label}</div></div>; }
function DataCard({ rows, type }: { rows: any[]; type: "states" | "locations" }) { return <Card className="glass-panel border-white/[0.06]"><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-white/10">{(type === "states" ? ["State", "Attempts", "Providers", "Verified", "Outreach"] : ["State", "City", "Attempts", "Providers", "Verified", "Outreach", "Gap"]).map((h) => <th key={h} className="text-left p-3 text-muted-foreground text-xs font-bold uppercase tracking-wider">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r, i) => type === "states" ? <tr key={`${r.state}-${i}`} className="border-b border-white/[0.04]"><td className="p-3 text-white font-bold">{safeText(r.state, "Unknown")}</td><td className="p-3">{n(r.totalAttempts)}</td><td className="p-3">{n(r.providers)}</td><td className="p-3 text-lime-300">{n(r.verifiedProviders)}</td><td className="p-3">{n(r.outreachAttempts)}</td></tr> : <tr key={`${r.state}-${r.city}-${i}`} className="border-b border-white/[0.04]"><td className="p-3 text-white font-bold">{safeText(r.state, "Unknown")}</td><td className="p-3">{safeText(r.city, "—")}</td><td className="p-3">{n(r.attempts)}</td><td className="p-3">{n(r.providers)}</td><td className="p-3 text-lime-300">{n(r.verifiedProviders)}</td><td className="p-3">{n(r.outreachAttempts)}</td><td className="p-3"><GapBadge value={safeText(r.gapScore, "Low")} /></td></tr>) : <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No rows match the current filter.</td></tr>}</tbody></table></CardContent></Card>; }
function GapBadge({ value }: { value: string }) { const cfg = GAP_CONFIG[value] || GAP_CONFIG.Low; return <span className="rounded-full px-2 py-1 text-[10px] font-bold uppercase border" style={{ color: cfg.color, background: cfg.bg, borderColor: cfg.border }}>{value}</span>; }
